
# This file has been generated at Mon Aug  9 15:16:54 2010

from openalea.core import *


__name__ = 'openalea.tutorial.functional'

__editable__ = True
__description__ = ''
__license__ = ''
__url__ = ''
__alias__ = []
__version__ = ''
__authors__ = ''
__institutes__ = ''
__icon__ = ''


__all__ = ['_164298348', 'TutOrder', '_164324300', 'Tut1', '_174563308', 'Tut3', 'Tut2', 'Tut4', '_164296780']



_164298348 = CompositeNodeFactory(name='Fibonacci (X and while multivariate)',
                             description='',
                             category='tutorial',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.flow control', 'X'),
   3: ('openalea.flow control', 'X'),
   4: ('openalea.data structure', 'int'),
   5: ('openalea.data structure', 'int'),
   6: ('openalea.data structure', 'int'),
   7: ('openalea.math', '>='),
   8: ('openalea.flow control', 'while multivariate'),
   9: ('openalea.math', '+'),
   10: ('openalea.python method', 'getitem'),
   11: ('openalea.data structure', 'int'),
   12: ('openalea.flow control', 'annotation'),
   14: ('openalea.flow control', 'annotation'),
   15: ('openalea.flow control', 'annotation'),
   16: ('openalea.flow control', 'annotation')},
                             elt_connections={  137719176: (7, 0, 8, 1),
   137719188: (2, 0, 7, 1),
   137719200: (2, 0, 10, 0),
   137719212: (3, 0, 9, 1),
   137719224: (4, 0, 8, 0),
   137719236: (2, 0, 9, 0),
   137719248: (11, 0, 10, 1),
   137719260: (9, 0, 8, 2),
   137719272: (10, 0, 8, 2),
   137719284: (5, 0, 8, 0),
   137719296: (6, 0, 7, 0),
   137719308: (3, 0, 10, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'Un',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x990bbcc> : "X"',
         'hide': True,
         'id': 2,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 393.60530654480965,
         'posy': 128.64071773245703,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'Un+1',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x990bbcc> : "X"',
         'hide': True,
         'id': 3,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 547.02795841447039,
         'posy': 130.68409678485639,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': '1',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x9cd4dac> : "int"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 37.567519329908244,
         'posy': 138.15330592838313,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': '1',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x9cd4dac> : "int"',
         'hide': True,
         'id': 5,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 93.866642707387214,
         'posy': 134.69317083425244,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': '10000000',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x9cd4dac> : "int"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 214.38280976153987,
         'posy': 131.23916709862843,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': '>=',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x95de3cc> : ">="',
         'hide': True,
         'id': 7,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 251.57630182988021,
         'posy': 226.08627369055145,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'while multivariate',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x990bcec> : "while multivariate"',
         'hide': True,
         'id': 8,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 175.99153955167736,
         'posy': 316.05578145090436,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': '+',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x95de7ec> : "+"',
         'hide': True,
         'id': 9,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 471.10278931732955,
         'posy': 153.02183825857369,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'getitem',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0x954c4ac> : "getitem"',
          'hide': True,
          'id': 10,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 436.51435965785998,
          'posy': 275.4205375639541,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   11: {  'block': False,
          'caption': '1',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0x9cd4dac> : "int"',
          'hide': True,
          'id': 11,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 523.8181071918342,
          'posy': 231.29252471276348,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   12: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 12,
          'posx': 23.160086667824125,
          'posy': 12.776873424348492,
          'txt': u'Fibonacci example using the multivariate node.'},
   14: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 14,
          'posx': 339.7605124239094,
          'posy': 95.037905573121506,
          'txt': u'U_{n+1} = U_n + U_{n+1}'},
   15: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 15,
          'posx': 29.699345491600454,
          'posy': 95.03790557312152,
          'txt': u'initial values'},
   16: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 16,
          'posx': 177.00809912993881,
          'posy': 95.631892482953532,
          'txt': u'max value'},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, "'x'")],
   3: [(0, "'Un+1'")],
   4: [(0, '1')],
   5: [(0, '1')],
   6: [(0, '10000000')],
   7: [],
   8: [],
   9: [],
   10: [],
   11: [(0, '1')],
   12: [],
   14: [],
   15: [],
   16: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [393.60530654480965, 128.64071773245703], 'userColor': None, 'useUserColor': False},
   3: {'position': [547.02795841447039, 130.68409678485639], 'userColor': None, 'useUserColor': False},
   4: {'position': [37.567519329908244, 138.15330592838313], 'userColor': None, 'useUserColor': False},
   5: {'position': [93.866642707387214, 134.69317083425244], 'userColor': None, 'useUserColor': False},
   6: {'position': [214.38280976153987, 131.23916709862843], 'userColor': None, 'useUserColor': False},
   7: {'position': [251.57630182988021, 226.08627369055145], 'userColor': None, 'useUserColor': False},
   8: {'position': [175.99153955167736, 316.05578145090436], 'userColor': None, 'useUserColor': False},
   9: {'position': [471.10278931732955, 153.02183825857369], 'userColor': None, 'useUserColor': False},
   10: {'position': [436.51435965785998, 275.4205375639541], 'userColor': None, 'useUserColor': False},
   11: {'position': [523.8181071918342, 231.29252471276348], 'userColor': None, 'useUserColor': False},
   12: {'color': None, 'position': [23.160086667824125, 12.776873424348492], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Fibonacci example using the multivariate node.</p></body></html>', 'rectP2': (655.40515630863911, 63.162050290591097), 'text': u'Fibonacci example using the multivariate node.'},
   14: {'color': None, 'position': [339.7605124239094, 95.037905573121506], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">U_{n+1} = U_n + U_{n+1}</p></body></html>', 'rectP2': (303.4034516779293, 136.64109079918649), 'text': u'U_{n+1} = U_n + U_{n+1}'},
   15: {'color': None, 'position': [29.699345491600454, 95.03790557312152], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">initial values</p></body></html>', 'rectP2': (131.0, 134.04879256469312), 'text': u'initial values'},
   16: {'color': None, 'position': [177.00809912993881, 95.631892482953532], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">max value</p></body></html>', 'rectP2': (152.21994167879188, 95.718172291647619), 'text': u'max value'},
   '__in__': {'position': [20.0, 5.0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [20.0, 250.0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




TutOrder = CompositeNodeFactory(name='TutOrder',
                             description='',
                             category='composite,tutorial',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.data structure', 'float'),
   3: ('openalea.data structure', 'float'),
   4: ('openalea.data structure', '#list'),
   5: ('openalea.data structure', 'float'),
   6: ('openalea.flow control', 'annotation'),
   7: ('openalea.flow control', 'annotation')},
                             elt_connections={  9794436: (5, 0, 4, 0), 9794448: (2, 0, 4, 0), 9794460: (3, 0, 4, 0)},
                             elt_data={  2: {  'block': False,
         'caption': '2.0',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 212.5,
         'posy': 133.75,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': '1.0',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 116.25,
         'posy': 136.25,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'list',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 217.5,
         'posy': 278.75,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': '3.0',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 300.0,
         'posy': 135.0,
         'priority': 0,
         'user_application': None},
   6: {  'posx': 311.25, 'posy': 288.75, 'txt': '[1.0, 2.0, 3.0]'},
   7: {  'posx': 87.5,
         'posy': 67.5,
         'txt': 'Create a list with multiple connections'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(0, '2.0')],
   3: [(0, '1.0')],
   4: [],
   5: [(0, '3.0')],
   6: [],
   7: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_164324300 = CompositeNodeFactory(name='While univariate',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.flow control', 'X'),
   3: ('openalea.flow control', 'while univariate'),
   4: ('openalea.math', '>='),
   5: ('openalea.data structure', 'int'),
   6: ('openalea.data structure', 'int'),
   7: ('openalea.math', '+'),
   8: ('openalea.data structure', 'int'),
   18: ('openalea.flow control', 'annotation'),
   19: ('openalea.flow control', 'annotation'),
   25: ('openalea.flow control', 'annotation'),
   30: ('openalea.flow control', 'annotation')},
                             elt_connections={  137719236: (6, 0, 7, 1),
   137719248: (7, 0, 3, 2),
   137719260: (2, 0, 4, 1),
   137719272: (2, 0, 7, 0),
   137719284: (8, 0, 3, 0),
   137719296: (5, 0, 4, 0),
   137719308: (4, 0, 3, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'X',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x990bbcc> : "X"',
         'hide': True,
         'id': 2,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 413.36750784627884,
         'posy': 186.97583036028982,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'while univariate',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x990bc6c> : "while univariate"',
         'hide': True,
         'id': 3,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 230.35020269017843,
         'posy': 344.14244093426549,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': '>=',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x95de3cc> : ">="',
         'hide': True,
         'id': 4,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 298.75,
         'posy': 217.5,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': '10',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x9cd4dac> : "int"',
         'hide': True,
         'id': 5,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 235.71817591673326,
         'posy': 161.98561884707794,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': '3',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x9cd4dac> : "int"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 506.08939680096557,
         'posy': 190.46740910698071,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': '+',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x95de7ec> : "+"',
         'hide': True,
         'id': 7,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 490.86370476141951,
         'posy': 254.9600189496133,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': '0',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x9cd4dac> : "int"',
         'hide': True,
         'id': 8,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 132.77359906917093,
         'posy': 167.19358897793657,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   18: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 18,
          'posx': 220.66295636818808,
          'posy': 104.25915608842317,
          'txt': u'Condition:\n    x <= 10'},
   19: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 19,
          'posx': 67.269574424520243,
          'posy': 107.77842143678654,
          'txt': u'init value:\n    x = 0'},
   25: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 25,
          'posx': 392.58968045262964,
          'posy': 104.25821704936801,
          'txt': u'iteration:\n   x += 3'},
   30: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 30,
          'posx': 70.069771721378714,
          'posy': 26.737149735789259,
          'txt': u'While univariate'},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, "'x'")],
   3: [],
   4: [],
   5: [(0, '10')],
   6: [(0, '3')],
   7: [],
   8: [(0, '0')],
   18: [],
   19: [],
   25: [],
   30: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [413.36750784627884, 186.97583036028982], 'useUserColor': False, 'userColor': None},
   3: {'position': [230.35020269017843, 344.14244093426549], 'useUserColor': False, 'userColor': None},
   4: {'position': [298.75, 217.5], 'useUserColor': False, 'userColor': None},
   5: {'position': [235.71817591673326, 161.98561884707794], 'useUserColor': False, 'userColor': None},
   6: {'position': [506.08939680096557, 190.46740910698071], 'useUserColor': False, 'userColor': None},
   7: {'position': [490.86370476141951, 254.9600189496133], 'useUserColor': False, 'userColor': None},
   8: {'position': [132.77359906917093, 167.19358897793657], 'useUserColor': False, 'userColor': None},
   18: {'color': None, 'position': [220.66295636818808, 104.25915608842317], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Condition:</p>\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    x &lt;= 10</p></body></html>', 'rectP2': (158.03987890518789, 173.75290277400154), 'text': u'Condition:\n    x <= 10'},
   19: {'color': None, 'position': [67.269574424520243, 107.77842143678654], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">init value:</p>\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    x = 0</p></body></html>', 'rectP2': (143.24659266428151, 108.23977799284452), 'text': u'init value:\n    x = 0'},
   25: {'color': None, 'position': [392.58968045262964, 104.25821704936801], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">iteration:</p>\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   x += 3</p></body></html>', 'rectP2': (182.85343005164782, 205.69243232058159), 'text': u'iteration:\n   x += 3'},
   30: {'color': None, 'position': [70.069771721378714, 26.737149735789259], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">While univariate</p></body></html>', 'rectP2': (503.13789658151745, 61.549267013611427), 'text': u'While univariate'},
   '__in__': {'position': [20.0, 5.0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [20.0, 250.0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




Tut1 = CompositeNodeFactory(name='Tut1',
                             description='',
                             category='composite,tutorial',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.python method', 'range'),
   3: ('openalea.function operator', 'map'),
   4: ('openalea.math', '+'),
   7: ('openalea.flow control', 'X'),
   8: ('openalea.data structure', 'int'),
   9: ('openalea.math', '*')},
                             elt_connections={  9794400: (9, 0, 3, 0),
   9794412: (4, 0, 9, 0),
   9794424: (8, 0, 9, 1),
   9794436: (8, 0, 4, 1),
   9794448: (7, 0, 4, 0),
   9794460: (2, 0, 3, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'range',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 366.25,
         'posy': 145.0,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'map',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 220.0,
         'posy': 297.5,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': '+',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 98.75,
         'posy': 138.75,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'X',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 50.0,
         'posy': 36.25,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': '5',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 172.5,
         'posy': 47.5,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': '*',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 131.25,
         'posy': 206.25,
         'priority': 0,
         'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(0, '0'), (1, '10'), (2, '1')],
   3: [],
   4: [],
   7: [(0, "'x'")],
   8: [(0, '5')],
   9: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_174563308 = CompositeNodeFactory(name='While multivariate',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.flow control', 'while multivariate'),
   3: ('openalea.data structure', '#list'),
   4: ('openalea.flow control', 'X'),
   5: ('openalea.flow control', 'X'),
   6: ('openalea.math', '*'),
   7: ('openalea.math', '>='),
   8: ('openalea.data structure', 'int'),
   9: ('openalea.math', '+'),
   10: ('openalea.data structure', 'int'),
   11: ('openalea.flow control', 'annotation'),
   13: ('openalea.flow control', 'annotation'),
   14: ('openalea.flow control', 'annotation'),
   15: ('openalea.flow control', 'annotation')},
                             elt_connections={  137719200: (5, 0, 9, 0),
   137719212: (4, 0, 6, 1),
   137719224: (6, 0, 2, 2),
   137719236: (5, 0, 6, 0),
   137719248: (10, 0, 7, 0),
   137719260: (5, 0, 7, 1),
   137719272: (8, 0, 9, 1),
   137719284: (9, 0, 2, 2),
   137719296: (7, 0, 2, 1),
   137719308: (3, 0, 2, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'while multivariate',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x990bcec> : "while multivariate"',
         'hide': True,
         'id': 2,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 296.07161168876803,
         'posy': -43.294389381234112,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'list',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x9cd4e2c> : "#list"',
         'hide': True,
         'id': 3,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 93.571611688768058,
         'posy': -244.29438938123411,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'X',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x990bbcc> : "X"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 596.82161168876803,
         'posy': -240.54438938123411,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'T',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x990bbcc> : "X"',
         'hide': True,
         'id': 5,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 443.1386562572751,
         'posy': -241.88280731563708,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': '*',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x95de94c> : "*"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 590.64020869970079,
         'posy': -164.29438938123411,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': '>=',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x95de3cc> : ">="',
         'hide': True,
         'id': 7,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 299.82161168876803,
         'posy': -239.04438938123411,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': '1',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x9cd4dac> : "int"',
         'hide': True,
         'id': 8,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 486.58229837171598,
         'posy': -239.77000133750283,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': '+',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x95de7ec> : "+"',
         'hide': True,
         'id': 9,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 456.86850230358505,
         'posy': -167.90594892227392,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': '10',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0x9cd4dac> : "int"',
          'hide': True,
          'id': 10,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 250.07161168876803,
          'posy': -268.04438938123411,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   11: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 11,
          'posx': 410.37074860429584,
          'posy': -328.37038777623076,
          'txt': u'while t <=10 :\n   x = x * t\n   t += 1'},
   13: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 13,
          'posx': 225.9253736333965,
          'posy': -330.0,
          'txt': u'Condition:\n    t<=10'},
   14: {  'factory': '<openalea.core.node.NodeFactory object at 0x97c284c> : "annotation"',
          'id': 14,
          'posx': 41.0,
          'posy': -330.19355190742482,
          'txt': u'init values:\n x = 0\n t = 0'},
   15: {  'factory': '<openalea.core.node.NodeFactory object at 0x96ed28c> : "annotation"',
          'id': 15,
          'posx': 42.0,
          'posy': -438.0,
          'txt': u'While multivariate example\n'},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [],
   3: [(0, '[1, 1]')],
   4: [(0, "'x'")],
   5: [(0, "'x'")],
   6: [],
   7: [],
   8: [(0, '1')],
   9: [],
   10: [(0, '10')],
   11: [],
   13: [],
   14: [],
   15: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [296.07161168876803, -43.294389381234112], 'useUserColor': False, 'userColor': None},
   3: {'position': [93.571611688768058, -244.29438938123411], 'useUserColor': False, 'userColor': None},
   4: {'position': [596.82161168876803, -240.54438938123411], 'useUserColor': False, 'userColor': None},
   5: {'position': [443.1386562572751, -241.88280731563708], 'useUserColor': False, 'userColor': None},
   6: {'position': [590.64020869970079, -164.29438938123411], 'useUserColor': False, 'userColor': None},
   7: {'position': [299.82161168876803, -239.04438938123411], 'useUserColor': False, 'userColor': None},
   8: {'position': [486.58229837171598, -239.77000133750283], 'useUserColor': False, 'userColor': None},
   9: {'position': [456.86850230358505, -167.90594892227392], 'useUserColor': False, 'userColor': None},
   10: {'position': [250.07161168876803, -268.04438938123411], 'useUserColor': False, 'userColor': None},
   11: {'color': None, 'position': [410.37074860429584, -328.37038777623076], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">while t &lt;=10 :</p>\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   x = x * t</p>\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">   t += 1</p></body></html>', 'rectP2': (273.0, 238.5), 'text': u'while t <=10 :\n   x = x * t\n   t += 1'},
   13: {'color': None, 'position': [225.9253736333965, -330.0], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">Condition:</p>\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">    t&lt;=10</p></body></html>', 'rectP2': (168.0, 137.5), 'text': u'Condition:\n    t<=10'},
   14: {'color': None, 'position': [41.0, -330.19355190742482], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">init values:</p>\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"> x = 0</p>\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"> t = 0</p></body></html>', 'rectP2': (174.0, 137.5), 'text': u'init values:\n x = 0\n t = 0'},
   15: {'color': None, 'position': [42.0, -438.0], 'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">While multivariate example</p>\n<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"></p></body></html>', 'rectP2': (642.0, 95.5), 'text': u'While multivariate example\n'},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




Tut3 = CompositeNodeFactory(name='Tut3',
                             description='',
                             category='composite,tutorial',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.python method', 'range'),
   3: ('openalea.flow control', 'annotation'),
   4: ('openalea.math', '>='),
   5: ('openalea.math', 'and'),
   6: ('openalea.math', '>='),
   7: ('openalea.flow control', 'X'),
   8: ('openalea.data structure', 'int'),
   9: ('openalea.data structure', 'int'),
   10: ('openalea.function operator', 'filter')},
                             elt_connections={  9789976: (9, 0, 4, 0),
   9789988: (7, 0, 4, 1),
   9790000: (2, 0, 10, 1),
   9790012: (6, 0, 5, 1),
   9790024: (8, 0, 6, 1),
   9790036: (5, 0, 10, 0),
   9790048: (4, 0, 5, 0),
   9790060: (7, 0, 6, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'range',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 496.25,
         'posy': 178.75,
         'priority': 0,
         'user_application': None},
   3: {  'posx': 366.25, 'posy': 28.75, 'txt': 'X <= 7 and X >= 2'},
   4: {  'block': False,
         'caption': '>=',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 146.25,
         'posy': 161.25,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'and',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 236.25,
         'posy': 256.25,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': '>=',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 268.75,
         'posy': 163.75,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'X',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 205.0,
         'posy': 42.5,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': '2',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 300.0,
         'posy': 67.5,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': '7',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 116.25,
         'posy': 82.5,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'filter',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 348.17901234567898,
          'posy': 325.29320987654319,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(0, '0'), (1, '10'), (2, '1')],
   3: [],
   4: [],
   5: [],
   6: [],
   7: [(0, "'x'")],
   8: [(0, '2')],
   9: [(0, '7')],
   10: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




Tut2 = CompositeNodeFactory(name='Tut2',
                             description='',
                             category='composite,tutorial',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.function operator', 'reduce'),
   3: ('openalea.flow control', 'X'),
   4: ('openalea.flow control', 'X'),
   5: ('openalea.math', '*'),
   6: ('openalea.python method', 'range'),
   7: ('openalea.flow control', 'annotation')},
                             elt_connections={  9790024: (6, 0, 2, 1),
   9790036: (5, 0, 2, 0),
   9790048: (4, 0, 5, 1),
   9790060: (3, 0, 5, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'reduce',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 262.5,
         'posy': 218.75,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'X0',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 218.75,
         'posy': 32.5,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'X1',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 307.5,
         'posy': 30.0,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': '*',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 257.5,
         'posy': 103.75,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'range',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 386.25,
         'posy': 112.5,
         'priority': 0,
         'user_application': None},
   7: {  'posx': 362.5, 'posy': 221.25, 'txt': 'Factorial with a reduce'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [],
   3: [(0, "'x1'")],
   4: [(0, "'x1'")],
   5: [],
   6: [(0, '1'), (1, '10'), (2, '1')],
   7: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




Tut4 = CompositeNodeFactory(name='Tut4',
                             description='',
                             category='composite,tutorial',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.data structure', '#list'),
   3: ('openalea.function operator', 'map'),
   4: ('openalea.flow control', 'X'),
   6: ('openalea.math', '>='),
   7: ('openalea.flow control', 'X'),
   8: ('openalea.data structure', 'int'),
   9: ('openalea.function operator', 'filter')},
                             elt_connections={  9794400: (7, 0, 6, 0),
   9794412: (8, 0, 6, 1),
   9794424: (6, 0, 9, 0),
   9794436: (4, 0, 9, 1),
   9794448: (9, 0, 3, 0),
   9794460: (2, 0, 3, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'list',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 433.75,
         'posy': 286.25,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'map',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 345.0,
         'posy': 368.75,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'X',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 376.25,
         'posy': 172.5,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': '>=',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 266.25,
         'posy': 215.0,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'X',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 175.0,
         'posy': 107.5,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': '7',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 297.5,
         'posy': 118.75,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'filter',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 290.0,
         'posy': 278.75,
         'priority': 0,
         'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [  (  0,
            '[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]')],
   3: [],
   4: [(0, "'x'")],
   6: [],
   7: [(0, "'x'")],
   8: [(0, '7')],
   9: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_164296780 = CompositeNodeFactory(name='multi_file',
                             description='',
                             category='composite,tutorial',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.function operator', 'map'),
   3: ('openalea.flow control', 'annotation'),
   4: ('openalea.file', 'glob'),
   5: ('openalea.file', 'dirname'),
   6: ('openalea.flow control', 'annotation'),
   7: ('openalea.data structure.string', 'string'),
   8: ('openalea.file', 'joinpath'),
   9: ('openalea.data structure.string', 'join'),
   10: ('openalea.data structure.string', 'string'),
   12: ('openalea.flow control', 'X'),
   13: ('openalea.flow control', 'annotation'),
   14: ('openalea.system', 'command')},
                             elt_connections={  9789976: (8, 0, 4, 0),
   9789988: (12, 0, 9, 0),
   9790000: (7, 0, 8, 0),
   9790012: (4, 0, 2, 1),
   9790024: (14, 0, 2, 0),
   9790036: (5, 0, 8, 0),
   9790048: (10, 0, 9, 0),
   9790060: (9, 0, 14, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'map',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 266.02157943067033,
         'posy': 287.39784205693297,
         'priority': 0,
         'user_application': None},
   3: {  'posx': 103.75, 'posy': 38.75, 'txt': 'Build command'},
   4: {  'block': False,
         'caption': 'glob',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 396.25,
         'posy': 211.25,
         'priority': 0,
         'user_application': None},
   5: {  'block': False,
         'caption': 'dirname',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 346.25,
         'posy': 73.75,
         'priority': 0,
         'user_application': None},
   6: {  'posx': 370.0, 'posy': 17.5, 'txt': 'Get a list of file'},
   7: {  'block': False,
         'caption': "'*.py'",
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 460.0,
         'posy': 73.75,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'joinpath',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 386.25,
         'posy': 150.0,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'join',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 157.5,
         'posy': 150.0,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': "'dos2unix'",
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 82.5,
          'posy': 78.75,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'Filename',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set(),
          'posx': 208.10146923783287,
          'posy': 72.674471992653793,
          'priority': 0,
          'user_application': None},
   13: {  'posx': 162.5, 'posy': 340.0, 'txt': 'Apply the command to each file'},
   14: {  'block': False,
          'caption': 'os.system',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 150.0,
          'posy': 220.0,
          'priority': 0,
          'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [],
   3: [],
   4: [],
   5: [(0, "'D:/Documents/pradal/devlp/aleapkg/adel/adel/geometry'")],
   6: [],
   7: [(0, "'*.py'")],
   8: [],
   9: [(1, "' '")],
   10: [(0, "'dos2unix'")],
   12: [(0, "'x'")],
   13: [],
   14: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




