
# This file has been generated at Thu Jul 15 14:38:16 2010

from openalea.core import *


__name__ = 'openalea.tutorial.multiprocess'

__editable__ = True
__description__ = ''
__license__ = ''
__url__ = ''
__alias__ = []
__version__ = ''
__authors__ = ''
__institutes__ = ''
__icon__ = ''


__all__ = ['_189873516', '_189872748', '_189871596']



_189873516 = CompositeNodeFactory(name='tutorial parallel_map',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.multiprocessing', 'parallel map'),
   3: ('openalea.function operator', 'function'),
   4: ('openalea.python method', 'range'),
   5: ('openalea.multiprocessing', 'parallel map'),
   6: ('openalea.flow control', 'X'),
   7: ('openalea.python method', 'range'),
   8: ('openalea.math', '*'),
   9: ('openalea.data structure', 'int'),
   10: ('openalea.flow control', 'annotation'),
   11: ('openalea.flow control', 'annotation')},
                             elt_connections={  161205696: (9, 0, 8, 1),
   161205708: (4, 0, 2, 1),
   161205720: (3, 0, 2, 0),
   161205732: (8, 0, 5, 0),
   161205744: (7, 0, 5, 1),
   161205756: (6, 0, 8, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'parallel map',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb3b56cc> : "parallel map"',
         'hide': True,
         'id': 2,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -195.0,
         'posy': 65.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'f',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb53286c> : "function"',
         'hide': True,
         'id': 3,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -237.95866700480522,
         'posy': -52.794126363888253,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'range',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb519dec> : "range"',
         'hide': True,
         'id': 4,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -79.0,
         'posy': -54.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'parallel map',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb3b56cc> : "parallel map"',
         'hide': True,
         'id': 5,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 108.42564121115043,
         'posy': 75.944633367843693,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'X0',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb319aac> : "X"',
         'hide': True,
         'id': 6,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 65.917273694497183,
         'posy': -51.447628249363646,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'range',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb519dec> : "range"',
         'hide': True,
         'id': 7,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 221.2101644455652,
         'posy': -43.859235823552595,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': '*',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb43bc0c> : "*"',
         'hide': True,
         'id': 8,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 84.406265096612231,
         'posy': 8.0386919139630635,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': '2',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb4c078c> : "int"',
         'hide': True,
         'id': 9,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 124.59972466642756,
         'posy': -49.839889866571035,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'factory': '<openalea.core.node.NodeFactory object at 0xb25ad4c> : "annotation"',
          'id': 10,
          'posx': -212.26618858133065,
          'posy': 133.05465967171213,
          'txt': u'launch  in a shell:\nipcluster local -n 2 '},
   11: {  'factory': '<openalea.core.node.NodeFactory object at 0xb25ad4c> : "annotation"',
          'id': 11,
          'posx': 100.95587017892555,
          'posy': 143.40910789519168,
          'txt': u'Error raised:\nFunctionType'},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [],
   3: [(0, "'def f(x):\\n  return x**2'")],
   4: [(0, '0'), (1, '100'), (2, '1')],
   5: [],
   6: [(0, "'x'")],
   7: [(0, '0'), (1, '100'), (2, '1')],
   8: [],
   9: [(0, '2')],
   10: [],
   11: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-195.0, 65.0], 'userColor': None, 'useUserColor': False},
   3: {'position': [-237.95866700480522, -52.794126363888253], 'userColor': None, 'useUserColor': False},
   4: {'position': [-79.0, -54.0], 'userColor': None, 'useUserColor': False},
   5: {'position': [108.42564121115043, 75.944633367843693], 'userColor': None, 'useUserColor': False},
   6: {'position': [65.917273694497183, -51.447628249363646], 'userColor': None, 'useUserColor': False},
   7: {'position': [221.2101644455652, -43.859235823552595], 'userColor': None, 'useUserColor': False},
   8: {'position': [84.406265096612231, 8.0386919139630635], 'userColor': None, 'useUserColor': False},
   9: {'position': [124.59972466642756, -49.839889866571035], 'userColor': None, 'useUserColor': False},
   10: {'position': [-212.26618858133065, 133.05465967171213], 'text': u'launch  in a shell:\nipcluster local -n 2 '},
   11: {'position': [100.95587017892555, 143.40910789519168], 'text': u'Error raised:\nFunctionType'},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_189872748 = CompositeNodeFactory(name='tutorial pmap',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  4: ('openalea.system', 'vprint'),
   5: ('openalea.multiprocessing', 'pmap'),
   6: ('openalea.flow control', 'X'),
   7: ('openalea.python method', 'range'),
   8: ('openalea.math', '*'),
   9: ('openalea.data structure', 'int'),
   10: ('openalea.data structure', 'int'),
   11: ('openalea.system', 'vprint'),
   12: ('openalea.flow control', 'X'),
   13: ('openalea.python method', 'range'),
   14: ('openalea.math', '*'),
   15: ('openalea.data structure', 'int'),
   16: ('openalea.function operator', 'map')},
                             elt_connections={  142929284: (5, 0, 4, 0),
   142929296: (16, 0, 11, 0),
   142929308: (6, 0, 8, 0),
   142929320: (9, 0, 8, 1),
   142929332: (12, 0, 14, 0),
   142929344: (13, 0, 16, 1),
   142929356: (15, 0, 14, 1),
   142929368: (8, 0, 5, 0),
   142929380: (7, 0, 5, 1),
   142929392: (10, 0, 5, 2),
   142929404: (14, 0, 16, 0)},
                             elt_data={  4: {  'block': False,
         'caption': 'vprint',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xa3b8e2c> : "vprint"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 179.51051806078576,
         'posy': 147.74320728036582,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'pmap',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xa3b858c> : "pmap"',
         'hide': True,
         'id': 5,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 162.04711469745487,
         'posy': 90.083699544272037,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'X0',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xa16cc6c> : "X"',
         'hide': True,
         'id': 6,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 65.917273694497183,
         'posy': -51.447628249363646,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'range',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xa362f6c> : "range"',
         'hide': True,
         'id': 7,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 221.2101644455652,
         'posy': -43.859235823552595,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': '*',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xa2bbdcc> : "*"',
         'hide': True,
         'id': 8,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 84.406265096612231,
         'posy': 8.0386919139630635,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': '2',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xa35094c> : "int"',
         'hide': True,
         'id': 9,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 124.59972466642756,
         'posy': -49.839889866571035,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': '4',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xa35094c> : "int"',
          'hide': True,
          'id': 10,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 258.8612055869886,
          'posy': 26.977611827032664,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   11: {  'block': False,
          'caption': 'vprint',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xa3b8e2c> : "vprint"',
          'hide': True,
          'id': 11,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -107.40376501951508,
          'posy': 138.16258974341375,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   12: {  'block': False,
          'caption': 'X0',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xa16cc6c> : "X"',
          'hide': True,
          'id': 12,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -201.36337445169835,
          'posy': -45.149721656008097,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   13: {  'block': False,
          'caption': 'range',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xa362f6c> : "range"',
          'hide': True,
          'id': 13,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -61.256317744752216,
          'posy': -29.968412208136129,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   14: {  'block': False,
          'caption': '*',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xa2bbdcc> : "*"',
          'hide': True,
          'id': 14,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -182.87438304958329,
          'posy': 14.336598507318584,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   15: {  'block': False,
          'caption': '2',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xa35094c> : "int"',
          'hide': True,
          'id': 15,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -142.68092347976796,
          'posy': -43.541983273215479,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   16: {  'block': False,
          'caption': 'map',
          'delay': 0,
          'factory': '<openalea.core.node.NodeFactory object at 0xa3b870c> : "map"',
          'hide': True,
          'id': 16,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': -115.89305783249556,
          'posy': 74.794646661662412,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  4: [(1, "'Value is'"), (2, 'False'), (3, "<type 'str'>")],
   5: [],
   6: [(0, "'x'")],
   7: [(0, '0'), (1, '100'), (2, '1')],
   8: [],
   9: [(0, '2')],
   10: [(0, '4')],
   11: [(1, "'Value is'"), (2, 'False'), (3, "<type 'str'>")],
   12: [(0, "'x'")],
   13: [(0, '0'), (1, '100'), (2, '1')],
   14: [],
   15: [(0, '2')],
   16: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-195.0, 65.0], 'useUserColor': False, 'userColor': None},
   3: {  'position': [-237.95866700480522, -52.794126363888253],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [179.51051806078576, 147.74320728036582],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [162.04711469745487, 90.083699544272037],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [65.917273694497183, -51.447628249363646],
         'useUserColor': False,
         'userColor': None},
   7: {  'position': [221.2101644455652, -43.859235823552595],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [84.406265096612231, 8.0386919139630635],
         'useUserColor': False,
         'userColor': None},
   9: {  'position': [124.59972466642756, -49.839889866571035],
         'useUserColor': False,
         'userColor': None},
   10: {  'position': [258.8612055869886, 26.977611827032664],
          'useUserColor': False,
          'userColor': None},
   11: {  'position': [-107.40376501951508, 138.16258974341375],
          'useUserColor': False,
          'userColor': None},
   12: {  'position': [-201.36337445169835, -45.149721656008097],
          'useUserColor': False,
          'userColor': None},
   13: {  'position': [-61.256317744752216, -29.968412208136129],
          'useUserColor': False,
          'userColor': None},
   14: {  'position': [-182.87438304958329, 14.336598507318584],
          'useUserColor': False,
          'userColor': None},
   15: {  'position': [-142.68092347976796, -43.541983273215479],
          'useUserColor': False,
          'userColor': None},
   16: {  'position': [-115.89305783249556, 74.794646661662412],
          'useUserColor': False,
          'userColor': None},
   '__in__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_189871596 = CompositeNodeFactory(name='x+1',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[{  'desc': '', 'interface': IFunction, 'name': 'f'}],
                             elt_factory={  2: ('openalea.flow control', 'X'),
   3: ('openalea.math', '+'),
   4: ('openalea.data structure', 'int')},
                             elt_connections={  167296484: (3, 0, '__out__', 0),
   167296496: (2, 0, 3, 0),
   167296508: (4, 0, 3, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'X0',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xd02068c> : "X"',
         'hide': True,
         'id': 2,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -749.0,
         'posy': -508.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': '+',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xd0ceeac> : "+"',
         'hide': True,
         'id': 3,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -700.0,
         'posy': -430.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': '0',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xd153fac> : "int"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -642.0,
         'posy': -506.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': -695.5,
                 'posy': -370.0,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, "'x'")], 3: [], 4: [(0, '1')], '__in__': [], '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-749.0, -508.0], 'useUserColor': False, 'userColor': None},
   3: {  'position': [-700.0, -430.0], 'useUserColor': False, 'userColor': None},
   4: {  'position': [-642.0, -506.0], 'useUserColor': False, 'userColor': None},
   '__in__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {  'position': [-695.5, -370.0],
                 'useUserColor': False,
                 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




