
# This file has been generated at Sun Mar  7 15:45:00 2010

from openalea.core import CompositeNodeFactory


__name__ = 'openalea.pylab.demo'

__editable__ = True
__description__ = 'pylab nodes.'
__license__ = 'CECILL-C'
__url__ = 'http://openalea.gforge.inria.fr/doc/openalea/pylab/doc/_build/html/contents.html'
__alias__ = []
__version__ = '0.8.0'
__authors__ = 'Thomas Cokelaer'
__institutes__ = 'INRIA/CIRAD'
__icon__ = 'icon.png'


__all__ = ['_184861484', '_184863020', '_184862124']



_184861484 = CompositeNodeFactory(name='pie demo',
                             description='',
                             category='data processing, visualization',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.data structure.array', 'array'),
   3: ('openalea.pylab.nodes', 'PyLabPie'),
   4: ('openalea.data structure.array', 'array')},
                             elt_connections={165978072: (2, 0, 3, 3), 165978084: (4, 0, 3, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'array',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -72.0,
         'posy': -460.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabPie',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -120.0,
         'posy': -398.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'array',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -131.0,
         'posy': -460.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, "'character'"), (1, "['c', 'r', 'b', 'y']")],
   3: [  (1, 'None'),
         (2, "'cryk'"),
         (4, '0.59999999999999998'),
         (5, '1.1000000000000001'),
         (6, 'True'),
         (7, 'False'),
         (8, 'None')],
   4: [(0, "'signed integer (4)'"), (1, '[10, 50, 30, 10]')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-72.0, -460.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-120.0, -398.0], 'useUserColor': False, 'userColor': None},
   4: {'position': [-131.0, -460.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




_184863020 = CompositeNodeFactory(name='plot and histogram demos',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  12: ('openalea.pylab.nodes', 'PyLabRandom'),
   13: ('openalea.pylab.nodes', 'PyLabHist'),
   14: ('openalea.pylab.nodes', 'PyLabRandom'),
   15: ('openalea.pylab.nodes', 'PyLabPlot'),
   16: ('openalea.pylab.nodes', 'PyLabRandom')},
                             elt_connections={  163127244: (12, 0, 13, 0),
   163127256: (16, 0, 15, 0),
   163127268: (14, 0, 15, 1)},
                             elt_data={  12: {  'block': False,
          'caption': 'PyLabRandom',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 81.665467837069713,
          'posy': -335.25823638375994,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   13: {  'block': False,
          'caption': 'PyLabHist',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 100.13720145560312,
          'posy': -196.42297208599072,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   14: {  'block': False,
          'caption': 'PyLabRandom',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': -89.204001568454288,
          'posy': -328.23895928239455,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   15: {  'block': False,
          'caption': 'PyLabPlot',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': -188.72011043555972,
          'posy': -202.200118323814,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   16: {  'block': False,
          'caption': 'PyLabRandom',
          'hide': True,
          'is_in_error_state': False,
          'is_user_application': False,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': -216.68765705336162,
          'posy': -329.01132789586558,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  12: [(0, '100'), (1, '0.0'), (2, '1.0')],
   13: [  (1, '10'),
          (2, "'blue'"),
          (3, 'False'),
          (4, 'False'),
          (5, "'bar'"),
          (6, "'mid'"),
          (7, "'vertical'"),
          (8, 'False'),
          (9, 'True'),
          (10, '2'),
          (11, "''"),
          (12, "''"),
          (13, "''"),
          (14, 'True'),
          (15, "{'alpha': 1.0, 'animated': False}")],
   14: [(0, '100'), (1, '0.0'), (2, '1.0')],
   15: [  (2, 'None'),
          (3, "'circle'"),
          (4, '10'),
          (5, "'solid'"),
          (6, "'blue'"),
          (7, "''"),
          (8, "''"),
          (9, "''"),
          (10, 'True'),
          (11, 'True'),
          (12, 'True'),
          (13, '1')],
   16: [(0, '100'), (1, '0.0'), (2, '1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [288.6401364299744, -256.94150474779997],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [104.22417316846372, -110.60524499510436],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [-83.905359133203234, -109.82565562438805],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-82.809464086679682, -254.38107182664064],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [163.14572383937528, -253.75096883447964],
         'useUserColor': False,
         'userColor': None},
   7: {  'position': [-214.82941816356805, -250.98882518119839],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [-164.84435552154977, -165.90786749265652],
         'useUserColor': False,
         'userColor': None},
   9: {'position': [40.0, -253.0], 'useUserColor': False, 'userColor': None},
   10: {  'position': [-102.7322689373179, -50.620182353086044],
          'useUserColor': False,
          'userColor': None},
   11: {  'position': [244.60775335455773, -110.60524499510437],
          'useUserColor': False,
          'userColor': None},
   12: {'position': [81.665467837069713, -335.25823638375994], 'userColor': None, 'useUserColor': False},
   13: {'position': [100.13720145560312, -196.42297208599072], 'userColor': None, 'useUserColor': False},
   14: {'position': [-89.204001568454288, -328.23895928239455], 'userColor': None, 'useUserColor': False},
   15: {'position': [-188.72011043555972, -202.200118323814], 'userColor': None, 'useUserColor': False},
   16: {'position': [-216.68765705336162, -329.01132789586558], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             )




_184862124 = CompositeNodeFactory(name='scatter demo',
                             description='scatter plot using pylab nodes',
                             category='data processing, visualization',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabScatter'),
   3: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabRandom'),
   5: ('openalea.pylab.nodes', 'PyLabRandom'),
   6: ('openalea.pylab.nodes', 'PyLabRandom'),
   7: ('openalea.data structure', 'int')},
                             elt_connections={  165978036: (6, 0, 2, 0),
   165978048: (7, 0, 5, 2),
   165978060: (3, 0, 2, 1),
   165978072: (5, 0, 2, 2),
   165978084: (4, 0, 2, 3)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabScatter',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -425.0,
         'posy': -365.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': True,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -438.0,
         'posy': -465.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -165.0,
         'posy': -467.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -304.0,
         'posy': -478.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -579.0,
         'posy': -473.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': '214',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -241.0,
         'posy': -546.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (4, 'None'),
         (5, "'circle'"),
         (6, "'blue'"),
         (7, "''"),
         (8, "''"),
         (9, "''"),
         (10, 'True'),
         (11, '0.5')],
   3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   4: [(0, '100'), (1, '0.0'), (2, '1.0')],
   5: [(0, '100'), (1, '1.0')],
   6: [(0, '100'), (1, '0.0'), (2, '1.0')],
   7: [(0, '214')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-425.0, -365.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-438.0, -465.0], 'useUserColor': False, 'userColor': None},
   4: {'position': [-165.0, -467.0], 'useUserColor': False, 'userColor': None},
   5: {'position': [-304.0, -478.0], 'useUserColor': False, 'userColor': None},
   6: {'position': [-579.0, -473.0], 'useUserColor': False, 'userColor': None},
   7: {'position': [-241.0, -546.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




