
# This file has been generated at Thu Apr  8 12:12:40 2010

from openalea.core import *


__name__ = 'openalea.pylab.test'

__editable__ = True
__description__ = 'pylab test.'
__license__ = 'CECILL-C'
__url__ = 'http://openalea.gforge.inria.fr/doc/openalea/pylab/doc/_build/html/contents.html'
__alias__ = []
__version__ = '0.8.0'
__authors__ = 'Thomas Cokelaer'
__institutes__ = 'INRIA/CIRAD'
__icon__ = 'icon.png'


__all__ = ['polar', '_364801612', 'hexbin', 'scatter', 'plot', 'fill', 'acorr', 'errorbar', 'pie', 'hist', 'step', '_365378988', 'contour', 'bar', '_364799276', 'cohere', 'quiver', 'boxplot', 'loglog', '_365544076']



polar = CompositeNodeFactory(name='polar',
                             description='polar test',
                             category='data processing, visualization',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabPolar'),
   3: ('openalea.pylab.nodes', 'PyLabRandom'),
   5: ('openalea.pylab.nodes', 'PyLabRandom')},
                             elt_connections={166518744: (3, 0, 2, 0), 166518756: (5, 0, 2, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabPolar',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -638.0,
         'posy': -1577.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -715.0,
         'posy': -1678.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -589.0,
         'posy': -1680.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(2, '{}')],
   3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   5: [(0, '100'), (1, '0.0'), (2, '1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-638.0, -1577.0],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [-715.0, -1678.0],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-589.0, -1680.0],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




_364801612 = CompositeNodeFactory(name='axhline/axvline',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.text', 'PyLabShow'),
   3: ('openalea.pylab.text', 'PyLabAxhline'),
   5: ('openalea.pylab.text', 'PyLabAxvline'),
   8: ('openalea.pylab.nodes', 'PyLabLine2D')},
                             elt_connections={  155045788: (3, 0, 2, 0),
   155045812: (5, 0, 2, 0),
   155045836: (8, 0, 3, 4),
   155045848: (8, 0, 5, 4)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabShow',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 146.87177060110253,
         'posy': 292.64596700242379,
         'priority': 0,
         'use_user_color': False,
         'user_application': True,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabAxhline',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 196.03438800659188,
         'posy': 139.46580670390424,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabAxvline',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 326.75341188814701,
         'posy': 140.6412225273119,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'PyLabLine2D',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 221.36707807558821,
         'posy': 11.524516946698441,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (  0,
            '[<matplotlib.lines.Line2D object at 0xe33b44c>, <matplotlib.lines.Line2D object at 0xe2cc26c>]')],
   3: [(0, '0.5'), (1, '0'), (2, '1'), (3, 'True')],
   5: [(0, '0.5'), (1, '0'), (2, '0.5'), (3, 'True')],
   8: [  (0, '[]'),
         (1, '[]'),
         (2, "'dashed'"),
         (3, "'red'"),
         (4, "'nothing'"),
         (5, '10'),
         (6, 'None'),
         (7, "'None'"),
         (8, '6.0'),
         (9, "'full'"),
         (10, 'None'),
         (11, '0.50000000000000011')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [146.87177060110253, 292.64596700242379],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [196.03438800659188, 139.46580670390424],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [326.75341188814701, 140.6412225273119],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [221.36707807558821, 11.524516946698441],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




hexbin = CompositeNodeFactory(name='hexbin',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabRandom'),
   3: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.text', 'PyLabColorMap'),
   5: ('openalea.pylab.nodes', 'PyLabHexBin'),
   6: ('openalea.pylab.text', 'PyLabAxis')},
                             elt_connections={  162123712: (6, 0, 5, 25),
   162123724: (2, 0, 5, 0),
   162123736: (3, 0, 5, 1),
   162123748: (4, 0, 5, 14)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -124.0,
         'posy': 12.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 11.0,
         'posy': -24.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabColorMap',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 77.0,
         'posy': 53.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabHexBin',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -111.14325693342897,
         'posy': 151.97077021020783,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'PyLabAxis',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 230.56313938317714,
         'posy': 14.81526165406143,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '10000'), (1, '0.0'), (2, '1.0')],
   3: [(0, '10000'), (1, '0.0'), (2, '1.0')],
   4: [(0, "'winter'"), (1, 'False'), (2, 'False')],
   5: [  (2, '[]'),
         (3, '20'),
         (4, "'linear'"),
         (5, "'linear'"),
         (6, 'None'),
         (7, '1.0'),
         (8, 'False'),
         (9, 'None'),
         (10, 'None'),
         (11, 'None'),
         (12, 'None'),
         (13, 'None'),
         (15, 'True'),
         (16, 'True'),
         (17, '1'),
         (18, "''"),
         (19, "''"),
         (20, "''"),
         (21, '1'),
         (22, 'True'),
         (23, 'True'),
         (24, '{}')],
   6: [(0, "'manual'"), (1, '0.0'), (2, '1.0'), (3, '0.0'), (4, '1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-124.0, 12.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [11.0, -24.0], 'useUserColor': False, 'userColor': None},
   4: {'position': [77.0, 53.0], 'useUserColor': False, 'userColor': None},
   5: {  'position': [-111.14325693342897, 151.97077021020783],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [230.56313938317714, 14.81526165406143],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




scatter = CompositeNodeFactory(name='scatter',
                             description='',
                             category='visualisation',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  3: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabRandom'),
   5: ('openalea.pylab.nodes', 'PyLabRandom'),
   6: ('openalea.data structure', 'int'),
   7: ('openalea.pylab.nodes', 'PyLabRandom'),
   8: ('openalea.pylab.nodes', 'PyLabScatter')},
                             elt_connections={  166518672: (6, 0, 3, 0),
   166518684: (4, 0, 8, 1),
   166518696: (6, 0, 4, 0),
   166518708: (7, 0, 8, 2),
   166518720: (6, 0, 5, 0),
   166518732: (6, 0, 7, 0),
   166518744: (5, 0, 8, 3),
   166518756: (3, 0, 8, 0)},
                             elt_data={  3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -270.0,
         'posy': -309.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -174.0,
         'posy': -255.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -81.0,
         'posy': -320.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': '100',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -157.0,
         'posy': -423.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -11.0,
         'posy': -258.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'PyLabScatter',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -244.60491125699002,
         'posy': -147.308533916849,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  3: [(1, '0.0'), (2, '1.0')],
   4: [(1, '0.0'), (2, '1.0')],
   5: [(1, '6.0'), (2, '200.0')],
   6: [(0, '100')],
   7: [(1, '1.0'), (2, '27.0')],
   8: [  (4, "'circle'"),
         (5, 'None'),
         (6, '0.5'),
         (7, 'True'),
         (8, 'True'),
         (9, '1'),
         (10, "''"),
         (11, "''"),
         (12, "''"),
         (13, '1'),
         (14, 'True'),
         (15, 'False'),
         (16, '{}'),
         (  17,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-233.72726536184558, -147.75861603335062],
         'useUserColor': False,
         'userColor': None},
   3: {'position': [-270.0, -309.0], 'userColor': None, 'useUserColor': False},
   4: {'position': [-174.0, -255.0], 'userColor': None, 'useUserColor': False},
   5: {'position': [-81.0, -320.0], 'userColor': None, 'useUserColor': False},
   6: {'position': [-157.0, -423.0], 'userColor': None, 'useUserColor': False},
   7: {'position': [-11.0, -258.0], 'userColor': None, 'useUserColor': False},
   8: {'position': [-244.60491125699002, -147.308533916849], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             )




plot = CompositeNodeFactory(name='plot',
                             description='',
                             category='visualisation',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabPlot'),
   3: ('openalea.pylab.nodes', 'PyLabRandom')},
                             elt_connections={148873188: (3, 0, 2, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabPlot',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -70.411436324420976,
         'posy': 22.883716805436816,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -68.0,
         'posy': -126.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (1, 'None'),
         (2, "'circle'"),
         (3, '10'),
         (4, "'solid'"),
         (5, "'blue'"),
         (6, 'True'),
         (7, 'True'),
         (8, '1'),
         (9, "''"),
         (10, "''"),
         (11, "''"),
         (12, '1'),
         (13, 'True'),
         (14, 'False'),
         (15, '{}'),
         (  16,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-70.411436324420976, 22.883716805436816],
         'useUserColor': False,
         'userColor': None},
   3: {'position': [-68.0, -126.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




fill = CompositeNodeFactory(name='fill',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.numpy.creation', 'arange'),
   3: ('openalea.data structure', 'float'),
   4: ('openalea.numpy.math', 'sin'),
   5: ('openalea.math', '*'),
   6: ('openalea.numpy.math', 'exp'),
   7: ('openalea.math', '*'),
   8: ('openalea.math', '*'),
   9: ('openalea.data structure', 'float'),
   11: ('openalea.pylab.nodes', 'PyLabFill'),
   13: ('openalea.pylab.patches', 'PyLabPatch')},
                             elt_connections={  148873068: (9, 0, 8, 0),
   148873080: (2, 0, 8, 1),
   148873092: (7, 0, 11, 1),
   148873104: (6, 0, 7, 0),
   148873116: (3, 0, 5, 1),
   148873128: (8, 0, 6, 0),
   148873140: (13, 0, 11, 4),
   148873152: (2, 0, 5, 0),
   148873164: (4, 0, 7, 1),
   148873176: (2, 0, 11, 0),
   148873188: (5, 0, 4, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'arange',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 69.678367075136492,
         'posy': -132.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': '12.5',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 179.5285790416209,
         'posy': -92.44936322524245,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'sin',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 227.34573013291413,
         'posy': 29.03204765534025,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': '*',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 154.97382577852437,
         'posy': -27.831591480251618,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'exp',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 116.20316273152991,
         'posy': 36.786180264739187,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': '*',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 161.43560295302348,
         'posy': 114.32750635872816,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': '*',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 3.7682398952458698,
         'posy': 21.27791504594137,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': '-5.0',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -15.0,
         'posy': -76.324006378193246,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   11: {  'block': False,
          'caption': 'PyLabFill',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 24.0,
          'posy': 214.0,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   13: {  'block': False,
          'caption': 'PyLabPatch',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 85.310505740614971,
          'posy': -206.8779764209913,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '0'), (1, '1.01'), (2, '0.01'), (3, "'float64'")],
   3: [(0, '12.52')],
   4: [],
   5: [],
   6: [],
   7: [],
   8: [],
   9: [(0, '-5.0')],
   11: [  (2, '1'),
          (3, "'green'"),
          (5, 'True'),
          (6, 'True'),
          (7, '1'),
          (8, "''"),
          (9, "''"),
          (10, "''"),
          (11, '1'),
          (12, 'True'),
          (13, 'False'),
          (14, '{}'),
          (  15,
             "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   13: [  (0, '1.0'),
          (1, '{}'),
          (2, "'None'"),
          (3, "'black'"),
          (4, "'blue'"),
          (5, 'None'),
          (6, 'True'),
          (7, 'None'),
          (8, "'solid'"),
          (9, 'None')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [69.678367075136492, -132.0],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [179.5285790416209, -92.44936322524245],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [227.34573013291413, 29.03204765534025],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [154.97382577852437, -27.831591480251618],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [116.20316273152991, 36.786180264739187],
         'useUserColor': False,
         'userColor': None},
   7: {  'position': [161.43560295302348, 114.32750635872816],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [3.7682398952458698, 21.27791504594137],
         'useUserColor': False,
         'userColor': None},
   9: {  'position': [-15.0, -76.324006378193246],
         'useUserColor': False,
         'userColor': None},
   10: {  'position': [314.16623298478987, -0.31935886837160865],
          'useUserColor': False,
          'userColor': None},
   11: {'position': [24.0, 214.0], 'useUserColor': False, 'userColor': None},
   12: {'position': [142.0, -176.0], 'useUserColor': False, 'userColor': None},
   13: {  'position': [85.310505740614971, -206.8779764209913],
          'useUserColor': False,
          'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




acorr = CompositeNodeFactory(name='acorr',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabAcorr')},
                             elt_connections={148873176: (2, 0, 4, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -223.55154371616749,
         'posy': -72.828753397912777,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabAcorr',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -181.61465287341048,
         'posy': 120.83524713091454,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '100'), (1, '0.0'), (2, '1.0')],
   4: [  (1, '10'),
         (2, 'False'),
         (3, 'True'),
         (4, "'none'"),
         (5, '{}'),
         (6, 'True'),
         (7, 'True'),
         (8, '1'),
         (9, "''"),
         (10, "''"),
         (11, "''"),
         (12, '1'),
         (13, 'True'),
         (14, 'False'),
         (15, '{}'),
         (  16,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-223.55154371616749, -72.828753397912777],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [-180.23062028703367, 66.21891799683344],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [-181.61465287341048, 120.83524713091454],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




errorbar = CompositeNodeFactory(name='errorbar',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabAbsolute'),
   3: ('openalea.math', '*'),
   4: ('openalea.math', '*'),
   5: ('openalea.pylab.nodes', 'PyLabAbsolute'),
   6: ('openalea.numpy.random', 'randn'),
   7: ('openalea.data structure', 'float'),
   8: ('openalea.numpy.random', 'randn'),
   9: ('openalea.pylab.nodes', 'PyLabErrorBar'),
   10: ('openalea.numpy.math', 'exp'),
   11: ('openalea.numpy.creation', 'arange'),
   12: ('openalea.python method', 'len'),
   13: ('openalea.math', '*'),
   14: ('openalea.data structure', 'float')},
                             elt_connections={  138841904: (2, 0, 3, 0),
   138841916: (11, 0, 9, 0),
   138841928: (12, 0, 6, 0),
   138841940: (10, 0, 9, 1),
   138841952: (5, 0, 13, 0),
   138841964: (11, 0, 4, 0),
   138841976: (4, 0, 10, 0),
   138841988: (7, 0, 13, 1),
   138842000: (3, 0, 9, 2),
   138842012: (13, 0, 9, 3),
   138842024: (12, 0, 8, 0),
   138842036: (7, 0, 3, 1),
   138842048: (11, 0, 12, 0),
   138842060: (8, 0, 2, 0),
   138842072: (14, 0, 4, 1),
   138842084: (6, 0, 5, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabAbsolute',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 114.3810807257224,
         'posy': 148.71328516799554,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': '*',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 166.8785407208369,
         'posy': 277.0404096004977,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': '*',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 11.330511105682803,
         'posy': 175.93419035064753,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabAbsolute',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 256.59690589860338,
         'posy': 147.04718294685898,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'randn',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 223.54294960538311,
         'posy': 75.106219249850184,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': '0.1',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 232.98645330727743,
         'posy': 199.26639479292061,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'randn',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 145.49068664875321,
         'posy': 76.772321470986725,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'PyLabErrorBar',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -47.0,
         'posy': 403.4231836628104,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'exp',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': -6.1686422260220581,
          'posy': 228.43165034576202,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   11: {  'block': False,
          'caption': 'arange',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': -23.667795557726862,
          'posy': 65.106219249850199,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   12: {  'block': False,
          'caption': 'len',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 106.60367924496467,
          'posy': -36.0,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   13: {  'block': False,
          'caption': '*',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 281.87346071106595,
          'posy': 277.31865774955054,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   14: {  'block': False,
          'caption': '-1.0',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set([]),
          'posx': 40.49576665852419,
          'posy': 123.43673035553297,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [],
   3: [],
   4: [],
   5: [],
   6: [],
   7: [(0, '0.10000000000000001')],
   8: [],
   9: [  (4, 'None'),
         (5, 'None'),
         (6, '{}'),
         (7, 'True'),
         (8, 'True'),
         (9, '1'),
         (10, "''"),
         (11, "''"),
         (12, "''"),
         (13, '1'),
         (14, 'True'),
         (15, 'False'),
         (16, '{}'),
         (  17,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   10: [],
   11: [(0, '0'), (1, '4.0'), (2, '0.10000000000000001'), (3, "'float64'")],
   12: [],
   13: [],
   14: [(0, '-1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [114.3810807257224, 148.71328516799554],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [166.8785407208369, 277.0404096004977],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [11.330511105682803, 175.93419035064753],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [256.59690589860338, 147.04718294685898],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [223.54294960538311, 75.106219249850184],
         'useUserColor': False,
         'userColor': None},
   7: {  'position': [232.98645330727743, 199.26639479292061],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [145.49068664875321, 76.772321470986725],
         'useUserColor': False,
         'userColor': None},
   9: {  'position': [-47.0, 403.4231836628104],
         'useUserColor': False,
         'userColor': None},
   10: {  'position': [-6.1686422260220581, 228.43165034576202],
          'useUserColor': False,
          'userColor': None},
   11: {  'position': [-23.667795557726862, 65.106219249850199],
          'useUserColor': False,
          'userColor': None},
   12: {  'position': [106.60367924496467, -36.0],
          'useUserColor': False,
          'userColor': None},
   13: {  'position': [281.87346071106595, 277.31865774955054],
          'useUserColor': False,
          'userColor': None},
   14: {  'position': [40.49576665852419, 123.43673035553297],
          'useUserColor': False,
          'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




pie = CompositeNodeFactory(name='pie',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  3: ('openalea.data structure.array', 'array'),
   4: ('openalea.data structure.array', 'array'),
   5: ('openalea.pylab.nodes', 'PyLabPie')},
                             elt_connections={148873176: (3, 0, 5, 0), 148873188: (4, 0, 5, 2)},
                             elt_data={  3: {  'block': False,
         'caption': 'array',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -275.0,
         'posy': -265.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'array',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -213.0,
         'posy': -265.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabPie',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -264.84873540429135,
         'posy': -158.58723670104985,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  3: [(0, "'signed integer (4)'"), (1, '[25, 25, 5, 40, 5]')],
   4: [(0, "'character'"), (1, "['a', 'b', 'c', 'd', 'e']")],
   5: [  (1, 'None'),
         (3, 'None'),
         (4, '0.59999999999999998'),
         (5, '1.1000000000000001'),
         (6, 'False'),
         (7, 'False'),
         (8, 'None'),
         (9, 'True'),
         (10, 'True'),
         (11, '1'),
         (12, "''"),
         (13, "''"),
         (14, "''"),
         (15, '1'),
         (16, 'True'),
         (17, 'False'),
         (18, '{}'),
         (  19,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-267.0, -145.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-275.0, -265.0], 'useUserColor': False, 'userColor': None},
   4: {'position': [-213.0, -265.0], 'useUserColor': False, 'userColor': None},
   5: {  'position': [-264.84873540429135, -158.58723670104985],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




hist = CompositeNodeFactory(name='hist',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabHist'),
   3: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabHist'),
   5: ('openalea.pylab.nodes', 'PyLabLine2D'),
   6: ('openalea.pylab.nodes', 'PyLabRandom'),
   7: ('openalea.pylab.nodes', 'PyLabLine2D'),
   8: ('openalea.pylab.nodes', 'PyLabRandom')},
                             elt_connections={  155045812: (8, 0, 7, 0),
   155045824: (5, 0, 2, 0),
   155045836: (6, 0, 5, 0),
   155045848: (7, 0, 2, 0),
   155045860: (3, 0, 4, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabHist',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([2, 9, 10, 12, 18, 21]),
         'posx': -260.08331056026896,
         'posy': 348.99667599928961,
         'priority': 0,
         'use_user_color': False,
         'user_application': True,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -303.27299703264094,
         'posy': -187.61424332344214,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabHist',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([2, 9, 10, 12, 18, 21]),
         'posx': -252.02112218533557,
         'posy': -90.777354686667564,
         'priority': 0,
         'use_user_color': False,
         'user_application': True,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabLine2D',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -50.083310560268956,
         'posy': 249.99667599928961,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -15.083310560268956,
         'posy': 130.99667599928961,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'PyLabLine2D',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -247.08331056026896,
         'posy': 211.99667599928961,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -193.08331056026896,
         'posy': 95.996675999289621,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (1, '10'),
         (2, "'blue'"),
         (3, 'False'),
         (4, 'False'),
         (5, "'bar'"),
         (6, "'mid'"),
         (7, "'vertical'"),
         (8, 'False'),
         (9, "''"),
         (10, 'True'),
         (11, 'True'),
         (12, '1'),
         (13, "''"),
         (14, "''"),
         (15, "''"),
         (16, '1'),
         (17, 'True'),
         (18, 'False'),
         (19, '{}'),
         (  20,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}"),
         (21, "{'alpha': 1.0, 'animated': False}")],
   3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   4: [  (1, '10'),
         (2, "'blue'"),
         (3, 'False'),
         (4, 'False'),
         (5, "'bar'"),
         (6, "'mid'"),
         (7, "'vertical'"),
         (8, 'False'),
         (9, "''"),
         (10, 'True'),
         (11, 'True'),
         (12, '1'),
         (13, "''"),
         (14, "''"),
         (15, "''"),
         (16, '1'),
         (17, 'True'),
         (18, 'False'),
         (19, '{}'),
         (  20,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}"),
         (21, "{'alpha': 1.0, 'animated': False}")],
   5: [  (1, 'None'),
         (2, "'solid'"),
         (3, "'purple'"),
         (4, "'circle'"),
         (5, '10'),
         (6, 'None'),
         (7, "'None'"),
         (8, '1.0'),
         (9, "'full'"),
         (10, "'test'"),
         (11, '0.40000000000000013')],
   6: [(0, '100'), (1, '0.0'), (2, '1.0')],
   7: [  (1, 'None'),
         (2, "'solid'"),
         (3, "'green'"),
         (4, "'circle'"),
         (5, '10'),
         (6, 'None'),
         (7, "'None'"),
         (8, '1.0'),
         (9, "'full'"),
         (10, "'testg'"),
         (11, '1.0')],
   8: [(0, '100'), (1, '0.0'), (2, '1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-260.08331056026896, 348.99667599928961],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [-303.27299703264094, -187.61424332344214],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [-252.02112218533557, -90.777354686667564],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-50.083310560268956, 249.99667599928961],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [-15.083310560268956, 130.99667599928961],
         'useUserColor': False,
         'userColor': None},
   7: {  'position': [-247.08331056026896, 211.99667599928961],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [-193.08331056026896, 95.996675999289621],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




step = CompositeNodeFactory(name='step',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.numpy.creation', 'array'),
   3: ('openalea.pylab.nodes', 'PyLabStep'),
   4: ('openalea.pylab.nodes', 'PyLabLine2D'),
   5: ('openalea.numpy.creation', 'array'),
   6: ('openalea.numpy.creation', 'logspace'),
   7: ('openalea.numpy.creation', 'logspace')},
                             elt_connections={138842060: (4, 0, 3, 0), 138842072: (2, 0, 4, 0), 138842084: (5, 0, 4, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'array',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -101.49173478120218,
         'posy': 47.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabStep',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -44.628095645610273,
         'posy': 505.78617938943478,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabLine2D',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -117.0,
         'posy': 261.53100219336949,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'array',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 44.544429362477047,
         'posy': 56.046488044298712,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'logspace',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -85.0,
         'posy': 0.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'logspace',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 67.0,
         'posy': 171.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (0, '[1, 2, 3, 4, 5]'),
         (1, "'float64'"),
         (2, 'True'),
         (3, "'C'"),
         (4, 'False'),
         (5, '0')],
   3: [  (1, 'None'),
         (2, "'circle'"),
         (3, '10'),
         (4, "'blue'"),
         (5, 'True'),
         (6, 'True'),
         (7, '1'),
         (8, "''"),
         (9, "''"),
         (10, "''"),
         (11, '1'),
         (12, 'True'),
         (13, 'False'),
         (14, '{}'),
         (  15,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   4: [  (2, "'solid'"),
         (3, "'red'"),
         (4, "'circle'"),
         (5, '10'),
         (6, 'None'),
         (7, "'None'"),
         (8, '1.0'),
         (9, "'full'"),
         (10, 'None'),
         (11, '1.0')],
   5: [  (0, '[2, 0, 5, 3, 9]'),
         (1, "'float64'"),
         (2, 'True'),
         (3, "'C'"),
         (4, 'False'),
         (5, '0')],
   6: [(0, '0'), (1, '100.0'), (2, '50'), (3, 'True'), (4, 'True')],
   7: [(0, '0'), (1, '10.0'), (2, '10.0'), (3, 'True'), (4, '10.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-101.49173478120218, 47.0],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [-44.628095645610273, 505.78617938943478],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [-117.0, 261.53100219336949],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [44.544429362477047, 56.046488044298712],
         'useUserColor': False,
         'userColor': None},
   6: {'position': [-85.0, 0.0], 'useUserColor': False, 'userColor': None},
   7: {'position': [67.0, 171.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




_365378988 = CompositeNodeFactory(name='axhspan/axvspan',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.patches', 'PyLabPatch'),
   3: ('openalea.pylab.patches', 'PyLabPatch'),
   4: ('openalea.pylab.text', 'PyLabFontProperties'),
   5: ('openalea.pylab.text', 'PyLabShow'),
   6: ('openalea.pylab.text', 'PyLabAxhspan'),
   7: ('openalea.pylab.text', 'PyLabAxvspan'),
   8: ('openalea.pylab.patches', 'PyLabPatch'),
   9: ('openalea.pylab.text', 'PyLabAxhspan'),
   10: ('openalea.pylab.text', 'PyLabLegend')},
                             elt_connections={  148873104: (9, 0, 5, 0),
   148873116: (2, 0, 7, 5),
   148873128: (10, 0, 5, 1),
   148873140: (3, 0, 6, 5),
   148873152: (6, 0, 5, 0),
   148873164: (7, 0, 5, 0),
   148873176: (8, 0, 9, 5),
   148873188: (4, 0, 10, 8)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabPatch',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 248.85628291948836,
         'posy': -111.9964885879107,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabPatch',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 75.492851768246808,
         'posy': -118.41735640832707,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabFontProperties',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 255.0,
         'posy': 160.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabShow',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 89.0,
         'posy': 272.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'PyLabAxhspan',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 62.0,
         'posy': 12.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'PyLabAxvspan',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 257.0,
         'posy': 4.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': True,
         'user_color': None},
   8: {  'block': False,
         'caption': 'PyLabPatch',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -86.039628793579169,
         'posy': -125.84900928016053,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'PyLabAxhspan',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -62.0,
         'posy': 16.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   10: {  'block': False,
          'caption': 'PyLabLegend',
          'hide': True,
          'lazy': False,
          'port_hide_changed': set([]),
          'posx': 181.0,
          'posy': 213.0,
          'priority': 0,
          'use_user_color': False,
          'user_application': None,
          'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (0, '0.80000000000000004'),
         (1, '{}'),
         (2, "'None'"),
         (3, "'black'"),
         (4, "'red'"),
         (5, 'None'),
         (6, 'True'),
         (7, 'None'),
         (8, "'solid'"),
         (9, 'None')],
   3: [  (0, '0.80000000000000004'),
         (1, '{}'),
         (2, "'None'"),
         (3, "'black'"),
         (4, "'blue'"),
         (5, 'None'),
         (6, 'True'),
         (7, 'None'),
         (8, "'solid'"),
         (9, 'None')],
   4: [  (0, "'serif'"),
         (1, "'normal'"),
         (2, "'normal'"),
         (3, "'normal'"),
         (4, "'normal'"),
         (5, "'medium'")],
   5: [],
   6: [  (0, '0.10000000000000001'),
         (1, '0.20000000000000001'),
         (2, '0.10000000000000001'),
         (3, '0.20000000000000001'),
         (4, 'True')],
   7: [  (0, '0.20000000000000001'),
         (1, '0.25'),
         (2, '0'),
         (3, '1'),
         (4, 'True')],
   8: [  (0, '0.80000000000000004'),
         (1, '{}'),
         (2, "'None'"),
         (3, "'black'"),
         (4, "'yellow'"),
         (5, 'None'),
         (6, 'True'),
         (7, 'None'),
         (8, "'solid'"),
         (9, 'None')],
   9: [(0, '0'), (1, '0.5'), (2, '0'), (3, '1'), (4, 'True')],
   10: [  (0, 'False'),
          (1, '0'),
          (2, '2'),
          (3, '1'),
          (4, 'True'),
          (5, '1'),
          (6, 'None'),
          (7, 'None')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [248.85628291948836, -111.9964885879107],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [75.492851768246808, -118.41735640832707],
         'useUserColor': False,
         'userColor': None},
   4: {'position': [255.0, 160.0], 'useUserColor': False, 'userColor': None},
   5: {'position': [89.0, 272.0], 'useUserColor': False, 'userColor': None},
   6: {'position': [62.0, 12.0], 'useUserColor': False, 'userColor': None},
   7: {'position': [257.0, 4.0], 'useUserColor': False, 'userColor': None},
   8: {  'position': [-86.039628793579169, -125.84900928016053],
         'useUserColor': False,
         'userColor': None},
   9: {'position': [-62.0, 16.0], 'useUserColor': False, 'userColor': None},
   10: {'position': [181.0, 213.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




contour = CompositeNodeFactory(name='contour',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabContour'),
   3: ('openalea.pylab.nodes', 'PyLabCLabel'),
   4: ('openalea.pylab.text', 'PyLabColorMap'),
   5: ('openalea.pylab.text', 'PyLabARange'),
   6: ('openalea.pylab.text', 'PyLabARange'),
   7: ('openalea.data structure', 'float'),
   8: ('openalea.pylab.text', 'PyLabMeshGrid'),
   9: ('openalea.pylab.text', 'PyLabData1')},
                             elt_connections={  160440184: (3, 0, 2, 9),
   160440196: (8, 0, 2, 0),
   160440208: (6, 0, 8, 1),
   160440220: (8, 0, 9, 0),
   160440232: (8, 1, 2, 1),
   160440244: (7, 0, 5, 2),
   160440256: (8, 1, 9, 1),
   160440268: (5, 0, 8, 0),
   160440280: (9, 0, 2, 2),
   160440292: (7, 0, 6, 2)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabContour',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -36.0,
         'posy': 363.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabCLabel',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 158.0,
         'posy': 231.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabColorMap',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 106.0,
         'posy': 155.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabARange',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -61.0,
         'posy': 44.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'PyLabARange',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 83.0,
         'posy': 43.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': '0.0',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 10.0,
         'posy': -40.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'PyLabMeshGrid',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -24.0,
         'posy': 118.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'PyLabData1',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 6.0,
         'posy': 261.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (3, 'None'),
         (4, 'True'),
         (5, '1.0'),
         (6, "'solid'"),
         (7, '1.0'),
         (8, 'None'),
         (10, 'True'),
         (11, 'True'),
         (12, '1'),
         (13, "''"),
         (14, "''"),
         (15, "''"),
         (16, '1'),
         (17, 'True'),
         (18, 'False'),
         (19, '{}'),
         (  20,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   3: [  (0, '10'),
         (1, 'True'),
         (2, 'True'),
         (3, '5'),
         (4, "'%1.3f'"),
         (5, "'black'")],
   4: [(0, "'prism'"), (1, 'False'), (2, 'False')],
   5: [(0, '-3.0'), (1, '3.0')],
   6: [(0, '-2.0'), (1, '2.0')],
   7: [(0, '0.02')],
   8: [],
   9: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-36.0, 363.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [158.0, 231.0], 'useUserColor': False, 'userColor': None},
   4: {'position': [106.0, 155.0], 'useUserColor': False, 'userColor': None},
   5: {'position': [-61.0, 44.0], 'useUserColor': False, 'userColor': None},
   6: {'position': [83.0, 43.0], 'useUserColor': False, 'userColor': None},
   7: {'position': [10.0, -40.0], 'useUserColor': False, 'userColor': None},
   8: {'position': [-24.0, 118.0], 'useUserColor': False, 'userColor': None},
   9: {'position': [6.0, 261.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




bar = CompositeNodeFactory(name='bar',
                             description='test',
                             category='visualisation',
                             doc='',
                             inputs=(),
                             outputs=(),
                             elt_factory={},
                             elt_connections={},
                             elt_data={},
                             elt_value={},
                             elt_ad_hoc={},
                             lazy=True,
                             )




_364799276 = CompositeNodeFactory(name='pcolor test',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.text', 'PyLabData1'),
   3: ('openalea.pylab.text', 'PyLabARange'),
   4: ('openalea.pylab.text', 'PyLabARange'),
   5: ('openalea.pylab.text', 'PyLabMeshGrid'),
   6: ('openalea.pylab.nodes', 'PyLabPcolor'),
   7: ('openalea.pylab.text', 'PyLabColorMap')},
                             elt_connections={  138842000: (5, 0, 6, 0),
   138842012: (3, 0, 5, 0),
   138842024: (5, 1, 6, 1),
   138842036: (7, 0, 6, 3),
   138842048: (5, 0, 2, 0),
   138842060: (2, 0, 6, 2),
   138842072: (4, 0, 5, 1),
   138842084: (5, 1, 2, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabData1',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 28.215909783897985,
         'posy': 228.1828489087068,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabARange',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -75.0,
         'posy': 22.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabARange',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 120.0,
         'posy': 17.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabMeshGrid',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 3.0,
         'posy': 133.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'PyLabPcolor',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -19.0,
         'posy': 397.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'PyLabColorMap',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 198.63119891409832,
         'posy': 223.88428693683085,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [],
   3: [(0, '-3.0'), (1, '3.0'), (2, '0.10000000000000001')],
   4: [(0, '-2.0'), (1, '2.0'), (2, '0.10000000000000001')],
   5: [],
   6: [  (4, 'True'),
         (5, 'True'),
         (6, '1'),
         (7, "''"),
         (8, "''"),
         (9, "''"),
         (10, '1'),
         (11, 'True'),
         (12, 'False'),
         (13, '{}'),
         (  14,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   7: [(0, "'jet'"), (1, 'False'), (2, 'False')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [28.215909783897985, 228.1828489087068],
         'useUserColor': False,
         'userColor': None},
   3: {'position': [-75.0, 22.0], 'useUserColor': False, 'userColor': None},
   4: {'position': [120.0, 17.0], 'useUserColor': False, 'userColor': None},
   5: {'position': [3.0, 133.0], 'useUserColor': False, 'userColor': None},
   6: {'position': [-19.0, 397.0], 'useUserColor': False, 'userColor': None},
   7: {  'position': [198.63119891409832, 223.88428693683085],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




cohere = CompositeNodeFactory(name='cohere',
                             description='test',
                             category='visualisation',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabCohere'),
   3: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabRandom')},
                             elt_connections={148643800: (3, 0, 2, 0), 148643812: (4, 0, 2, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabCohere',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -73.0,
         'posy': 32.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -86.0,
         'posy': -146.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 41.0,
         'posy': -145.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (2, '16'),
         (3, '2.0'),
         (4, "'none'"),
         (5, '0'),
         (6, 'None'),
         (7, "'default'"),
         (8, '0'),
         (9, 'True'),
         (10, 'True'),
         (11, "''"),
         (12, "''"),
         (13, "''"),
         (14, "{'num': 1}"),
         (15, "{'legend on': True}"),
         (16, '{}'),
         (  17,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   4: [(0, '100'), (1, '0.0'), (2, '1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-73.0, 32.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-86.0, -146.0], 'useUserColor': False, 'userColor': None},
   4: {'position': [41.0, -145.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




quiver = CompositeNodeFactory(name='quiver',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.numpy.creation', 'arange'),
   3: ('openalea.pylab.text', 'PyLabMeshGrid'),
   4: ('openalea.numpy.creation', 'arange'),
   5: ('openalea.pylab.nodes', 'PyLabQuiver'),
   6: ('openalea.numpy.math', 'cos')},
                             elt_connections={  138842024: (3, 0, 5, 0),
   138842036: (3, 0, 6, 0),
   138842048: (6, 0, 5, 2),
   138842060: (4, 0, 3, 1),
   138842072: (2, 0, 3, 0),
   138842084: (3, 1, 5, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'arange',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -7.5681804322040591,
         'posy': 44.923554348998181,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabMeshGrid',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 20.86363913559191,
         'posy': 187.08265218797797,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'arange',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 77.388434791985304,
         'posy': 42.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabQuiver',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -36.0,
         'posy': 414.53720873034558,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'cos',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': 63.51136848728585,
         'posy': 300.80993045916182,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (0, '0'),
         (1, '6.2800000000000002'),
         (2, '0.20000000000000001'),
         (3, "'float64'")],
   3: [],
   4: [  (0, '0'),
         (1, '6.2800000000000002'),
         (2, '0.20000000000000001'),
         (3, "'float64'")],
   5: [  (3, 'None'),
         (4, 'None'),
         (5, "'width'"),
         (6, "'uv'"),
         (7, 'None'),
         (8, 'None'),
         (9, '3'),
         (10, '5'),
         (11, '4.5'),
         (12, '1'),
         (13, '1'),
         (14, "'tail'"),
         (15, "'None'"),
         (16, '{}'),
         (17, 'True'),
         (18, 'True'),
         (19, '1'),
         (20, "''"),
         (21, "''"),
         (22, "''"),
         (23, '1'),
         (24, 'True'),
         (25, 'False'),
         (26, '{}'),
         (  27,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   6: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-7.5681804322040591, 44.923554348998181],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [20.86363913559191, 187.08265218797797],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [77.388434791985304, 42.0],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-36.0, 414.53720873034558],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [63.51136848728585, 300.80993045916182],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




boxplot = CompositeNodeFactory(name='boxplot',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabRandom'),
   3: ('openalea.pylab.nodes', 'PyLabRandom'),
   5: ('openalea.pylab.nodes', 'PyLabRandom'),
   6: ('openalea.pylab.nodes', 'PyLabBoxPlot')},
                             elt_connections={147640232: (5, 0, 6, 0), 147640244: (3, 0, 6, 0), 147640256: (2, 0, 6, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -263.0,
         'posy': 80.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -134.0,
         'posy': 79.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -1.0,
         'posy': 78.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'PyLabBoxPlot',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -179.42407407407407,
         'posy': 189.19814814814819,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '100'), (1, '0.0'), (2, '1.0')],
   3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   5: [(0, '100'), (1, '0.0'), (2, '1.0')],
   6: [  (1, '0'),
         (2, "'circle'"),
         (3, '1'),
         (4, 'True'),
         (5, 'True'),
         (6, '1'),
         (7, "''"),
         (8, "''"),
         (9, "''"),
         (10, "{'num': 1}"),
         (11, "{'legend on': True}"),
         (12, 'False'),
         (13, '{}'),
         (  14,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-263.0, 80.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-134.0, 79.0], 'useUserColor': False, 'userColor': None},
   4: {  'position': [-206.75415573053368, 206.62992125984255],
         'useUserColor': False,
         'userColor': None},
   5: {'position': [-1.0, 78.0], 'useUserColor': False, 'userColor': None},
   6: {  'position': [-179.42407407407407, 189.19814814814819],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




loglog = CompositeNodeFactory(name='loglog',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabLogLog')},
                             elt_connections={148873188: (2, 0, 4, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -183.0,
         'posy': -85.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabLogLog',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -122.11780674823135,
         'posy': 108.20565154906575,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '100'), (1, '0.0'), (2, '1.0')],
   4: [  (1, 'None'),
         (2, "'circle'"),
         (3, '10'),
         (4, "'solid'"),
         (5, "'blue'"),
         (6, 'True'),
         (7, 'True'),
         (8, '1'),
         (9, "''"),
         (10, "''"),
         (11, "''"),
         (12, '1'),
         (13, 'True'),
         (14, 'False'),
         (15, '{}'),
         (  16,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-183.0, -85.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-176.0, 19.0], 'useUserColor': False, 'userColor': None},
   4: {  'position': [-122.11780674823135, 108.20565154906575],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




_365544076 = CompositeNodeFactory(name='annotation/bboc/yaarow',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=(),
                             outputs=(),
                             elt_factory={},
                             elt_connections={},
                             elt_data={},
                             elt_value={},
                             elt_ad_hoc={},
                             lazy=True,
                             )




