
# This file has been generated at Wed Mar 17 14:07:33 2010

from openalea.core import *


__name__ = 'openalea.pylab.test'

__editable__ = True
__description__ = 'pylab test.'
__license__ = 'CECILL-C'
__url__ = 'http://openalea.gforge.inria.fr/doc/openalea/pylab/doc/_build/html/contents.html'
__alias__ = []
__version__ = '0.8.0'
__authors__ = 'Thomas Cokelaer'
__institutes__ = 'INRIA/CIRAD'
__icon__ = 'icon.png'


__all__ = ['polar', 'bar', 'plot', 'acorr', 'pie', 'boxplot', 'hist', 'cohere', 'scatter', 'loglog']



polar = CompositeNodeFactory(name='polar',
                             description='polar test',
                             category='data processing, visualization',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabPolar'),
   3: ('openalea.pylab.nodes', 'PyLabRandom'),
   5: ('openalea.pylab.nodes', 'PyLabRandom')},
                             elt_connections={163127244: (3, 0, 2, 0), 163127268: (5, 0, 2, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabPolar',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -638.0,
         'posy': -1577.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -715.0,
         'posy': -1678.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -589.0,
         'posy': -1680.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(2, '{}')],
   3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   5: [(0, '100'), (1, '0.0'), (2, '1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-638.0, -1577.0],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [-715.0, -1678.0],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-589.0, -1680.0],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




bar = CompositeNodeFactory(name='bar',
                             description='test',
                             category='visualisation',
                             doc='',
                             inputs=(),
                             outputs=(),
                             elt_factory={},
                             elt_connections={},
                             elt_data={},
                             elt_value={},
                             elt_ad_hoc={},
                             lazy=True,
                             )




plot = CompositeNodeFactory(name='plot',
                             description='',
                             category='visualisation',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabPlot'),
   3: ('openalea.pylab.nodes', 'PyLabRandom')},
                             elt_connections={163557348: (3, 0, 2, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabPlot',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -90.0,
         'posy': -25.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -68.0,
         'posy': -126.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (1, 'None'),
         (2, "'circle'"),
         (3, '10'),
         (4, "'solid'"),
         (5, "'blue'"),
         (6, 'True'),
         (7, 'True'),
         (8, "''"),
         (9, "''"),
         (10, "''"),
         (11, "{'num': 1}"),
         (12, "{'legend on': True}"),
         (13, '{}'),
         (  14,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-90.0, -25.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-68.0, -126.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




acorr = CompositeNodeFactory(name='acorr',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabAcorr')},
                             elt_connections={163557348: (2, 0, 4, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -223.55154371616749,
         'posy': -72.828753397912777,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabAcorr',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -219.41155757681031,
         'posy': 41.597330162437501,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '100'), (1, '0.0'), (2, '1.0')],
   4: [  (1, '10'),
         (2, 'False'),
         (3, 'True'),
         (4, "'none'"),
         (5, '{}'),
         (6, 'True'),
         (7, 'True'),
         (8, "''"),
         (9, "''"),
         (10, "''"),
         (11, "{'num': 1}"),
         (12, "{'legend on': True}"),
         (13, '{}'),
         (  14,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-223.55154371616749, -72.828753397912777],
         'useUserColor': False,
         'userColor': None},
   3: {'position': [-183.0, 133.0], 'useUserColor': False, 'userColor': None},
   4: {  'position': [-219.41155757681031, 41.597330162437501],
         'useUserColor': False,
         'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




pie = CompositeNodeFactory(name='pie',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabPie'),
   3: ('openalea.data structure.array', 'array'),
   4: ('openalea.data structure.array', 'array')},
                             elt_connections={163557336: (3, 0, 2, 0), 163557348: (4, 0, 2, 2)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabPie',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -267.0,
         'posy': -145.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'array',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -275.0,
         'posy': -265.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'array',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -213.0,
         'posy': -265.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (0, "array('l', [25, 25, 5, 40, 5])"),
         (1, 'None'),
         (2, "array('c', 'abcde')"),
         (3, 'None'),
         (4, '0.59999999999999998'),
         (5, '1.1000000000000001'),
         (6, 'False'),
         (7, 'False'),
         (8, 'None'),
         (9, 'True'),
         (10, 'True'),
         (11, "''"),
         (12, "''"),
         (13, "''"),
         (14, "{'num': 1}"),
         (15, "{'legend on': True}"),
         (16, '{}'),
         (  17,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   3: [(0, "'signed integer (4)'"), (1, '[25, 25, 5, 40, 5]')],
   4: [(0, "'character'"), (1, "['a', 'b', 'c', 'd', 'e']")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-267.0, -145.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-275.0, -265.0], 'useUserColor': False, 'userColor': None},
   4: {'position': [-213.0, -265.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




boxplot = CompositeNodeFactory(name='boxplot',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabRandom'),
   3: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabBoxPlot'),
   5: ('openalea.pylab.nodes', 'PyLabRandom')},
                             elt_connections={148643788: (5, 0, 4, 0), 148643800: (3, 0, 4, 0), 148643812: (2, 0, 4, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -263.0,
         'posy': 80.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -134.0,
         'posy': 79.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabBoxPlot',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -206.75415573053368,
         'posy': 206.62992125984255,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -1.0,
         'posy': 78.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '100'), (1, '0.0'), (2, '1.0')],
   3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   4: [  (1, '0'),
         (2, "'circle'"),
         (3, '1'),
         (4, 'True'),
         (5, 'True'),
         (6, "''"),
         (7, 'True'),
         (8, '1'),
         (9, "{'num': 1}"),
         (10, "{'legend on': True}"),
         (11, '{}'),
         (  12,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   5: [(0, '100'), (1, '0.0'), (2, '1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-263.0, 80.0], 'userColor': None, 'useUserColor': False},
   3: {'position': [-134.0, 79.0], 'userColor': None, 'useUserColor': False},
   4: {'position': [-206.75415573053368, 206.62992125984255], 'userColor': None, 'useUserColor': False},
   5: {'position': [-1.0, 78.0], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             )




hist = CompositeNodeFactory(name='hist',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  3: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabHist')},
                             elt_connections={148643812: (3, 0, 4, 0)},
                             elt_data={  3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -303.27299703264094,
         'posy': -187.61424332344214,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabHist',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -313.23442136498511,
         'posy': -92.195845697329389,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   4: [  (1, '10'),
         (2, "'blue'"),
         (3, 'False'),
         (4, 'False'),
         (5, "'bar'"),
         (6, "'mid'"),
         (7, "'vertical'"),
         (8, 'False'),
         (9, 'None'),
         (10, 'True'),
         (11, 'True'),
         (12, "''"),
         (13, "''"),
         (14, "''"),
         (15, "{'num': 1}"),
         (16, "{'legend on': True}"),
         (17, '{}'),
         (  18,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}"),
         (19, "{'alpha': 1.0, 'animated': False}")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-308.0, 24.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-303.27299703264094, -187.61424332344214], 'userColor': None, 'useUserColor': False},
   4: {'position': [-313.23442136498511, -92.195845697329389], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             )




cohere = CompositeNodeFactory(name='cohere',
                             description='test',
                             category='visualisation',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabCohere'),
   3: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabRandom')},
                             elt_connections={148643800: (3, 0, 2, 0), 148643812: (4, 0, 2, 1)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabCohere',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -73.0,
         'posy': 32.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -86.0,
         'posy': -146.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': 41.0,
         'posy': -145.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (2, '16'),
         (3, '2.0'),
         (4, "'none'"),
         (5, '0'),
         (6, 'None'),
         (7, "'default'"),
         (8, '0'),
         (9, 'True'),
         (10, 'True'),
         (11, "''"),
         (12, "''"),
         (13, "''"),
         (14, "{'num': 1}"),
         (15, "{'legend on': True}"),
         (16, '{}'),
         (  17,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   3: [(0, '100'), (1, '0.0'), (2, '1.0')],
   4: [(0, '100'), (1, '0.0'), (2, '1.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-73.0, 32.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-86.0, -146.0], 'useUserColor': False, 'userColor': None},
   4: {'position': [41.0, -145.0], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




scatter = CompositeNodeFactory(name='scatter',
                             description='',
                             category='visualisation',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabScatter'),
   3: ('openalea.pylab.nodes', 'PyLabRandom'),
   4: ('openalea.pylab.nodes', 'PyLabRandom'),
   5: ('openalea.pylab.nodes', 'PyLabRandom'),
   6: ('openalea.data structure', 'int'),
   7: ('openalea.pylab.nodes', 'PyLabRandom')},
                             elt_connections={  148643728: (6, 0, 7, 0),
   148643740: (7, 0, 2, 3),
   148643752: (5, 0, 2, 2),
   148643764: (6, 0, 5, 0),
   148643776: (6, 0, 4, 0),
   148643788: (6, 0, 3, 0),
   148643800: (4, 0, 2, 1),
   148643812: (3, 0, 2, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabScatter',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -151.0,
         'posy': -70.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': True,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -270.0,
         'posy': -309.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -174.0,
         'posy': -255.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -81.0,
         'posy': -320.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': '100',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set([]),
         'posx': -157.0,
         'posy': -423.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -11.0,
         'posy': -258.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [  (4, 'None'),
         (5, "'circle'"),
         (6, "'blue'"),
         (7, '0.5'),
         (8, 'True'),
         (9, 'True'),
         (10, "''"),
         (11, "''"),
         (12, "''"),
         (13, "{'num': 1}"),
         (14, "{'legend on': False}"),
         (15, '{}'),
         (  16,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   3: [(1, '0.0'), (2, '1.0')],
   4: [(1, '0.0'), (2, '1.0')],
   5: [(1, '6.0'), (2, '200.0')],
   6: [(0, '100')],
   7: [(1, '1.0'), (2, '27.0')],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-151.0, -70.0], 'userColor': None, 'useUserColor': False},
   3: {'position': [-270.0, -309.0], 'userColor': None, 'useUserColor': False},
   4: {'position': [-174.0, -255.0], 'userColor': None, 'useUserColor': False},
   5: {'position': [-81.0, -320.0], 'userColor': None, 'useUserColor': False},
   6: {'position': [-157.0, -423.0], 'userColor': None, 'useUserColor': False},
   7: {'position': [-11.0, -258.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             )




loglog = CompositeNodeFactory(name='loglog',
                             description='',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.pylab.nodes', 'PyLabRandom'),
   3: ('openalea.pylab.nodes', 'PyLabLogLog')},
                             elt_connections={142434276: (2, 0, 3, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'PyLabRandom',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -183.0,
         'posy': -85.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'PyLabLogLog',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': False,
         'port_hide_changed': set([]),
         'posx': -176.0,
         'posy': 19.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set([]),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set([]),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '100'), (1, '0.0'), (2, '1.0')],
   3: [  (1, 'None'),
         (2, "'circle'"),
         (3, '10'),
         (4, "'solid'"),
         (5, "'blue'"),
         (6, 'True'),
         (7, 'True'),
         (8, "''"),
         (9, "''"),
         (10, "''"),
         (11, "{'num': 1}"),
         (12, "{'legend on': True}"),
         (13, '{}'),
         (  14,
            "{'xmin': None, 'ymin': None, 'type': 'normal', 'ymax': None, 'xmax': None}")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-183.0, -85.0], 'useUserColor': False, 'userColor': None},
   3: {'position': [-176.0, 19.0], 'useUserColor': False, 'userColor': None},
   '__in__': {'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




