# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'openalea.OALab'
__version__ = '1.0.0'
__license__ = 'CeCILL-C'
__author__ = 'Guillaume Baty, Julien Coste, Christophe Pradal'
__institutes__ = 'CIRAD, INRIA'
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = ''
__alias__ = []

# Declare interfaces
from openalea.oalab.interfaces.all import (IApplet, IParadigmApplet, 
                                           IQTextWidget, IHelper)
__all__ = ['IApplet', 'IParadigmApplet', 'IQTextWidget', 'IHelper']

# Declare object factories
from openalea.oalab.legacy.catalog.factories import ObjectFactory
HelpWidget = ObjectFactory(name='HelpWidget', 
                          description="Help Widget", 
                          category="helpers", 
                          interfaces=["IHelper"], 
                          nodemodule="openalea.oalab.gui.help", 
                          nodeclass="HelpWidget")
__all__.append('HelpWidget')

LPyApplet = ObjectFactory(name='LPyApplet', 
                          description="LPyApplet", 
                          category="applets", 
                          interfaces=["IParadigmApplet"], 
                          nodemodule="openalea.oalab.plugins.lpy", 
                          nodeclass="LPyApplet")
__all__.append('LPyApplet')


PythonApplet = ObjectFactory(name='PythonApplet', 
                          description="PythonApplet", 
                          category="applets", 
                          interfaces=["IParadigmApplet"], 
                          nodemodule="openalea.oalab.plugins.python", 
                          nodeclass="PythonApplet")
__all__.append('PythonApplet')


RApplet = ObjectFactory(name='RApplet', 
                          description="RApplet", 
                          category="applets", 
                          interfaces=["IParadigmApplet"], 
                          nodemodule="openalea.oalab.plugins.r", 
                          nodeclass="RApplet")
__all__.append('RApplet')


VisualeaApplet = ObjectFactory(name='VisualeaApplet', 
                          description="VisualeaApplet", 
                          category="applets", 
                          interfaces=["IParadigmApplet"], 
                          nodemodule="openalea.oalab.plugins.visualea", 
                          nodeclass="VisualeaApplet")
__all__.append('VisualeaApplet')

