# This file has been automatically generated by pkg_builder

from openalea.core import *

__name__ = 'OALab'
__version__ = '1.0.0'
__license__ = 'CeCILL-C'
__author__ = 'Julien Coste, Christophe Pradal'
__institutes__ = 'CIRAD, INRIA'
__description__ = ''
__url__ = 'http://openalea.gforge.inria.fr'

__editable__ = 'True'
__icon__ = ''
__alias__ = []

__all__ = []

scenereader = Factory( name="scene reader",
              description="Read data from the data scene.",
              category="oalab control",
              nodemodule="openalea.oalab_wralea.oalabnode",
              nodeclass="SceneReader",
              inputs = (dict(name='Key', interface=IStr),),
              outputs = (dict(name='Obj', interface=None),),
              lazy = False,
              
              )
    
__all__.append('scenereader')

scenewriter = Factory(name="scene writer",
             description="Write data to the data scene.",
             category="flow control",
             nodemodule="openalea.oalab_wralea.oalabnode",
             nodeclass="SceneWriter",
             inputs = (dict(name='Key', interface=IStr),
                       dict(name='Obj', interface=None),),
             outputs = (dict(name='Obj', interface=None),),
             lazy = False,
             )

__all__.append('scenewriter')

scene_rw = Factory(name="scene setdefault",
             description="scene.setdefault(key,value).",
             category="flow control",
             nodemodule="openalea.oalab_wralea.oalabnode",
             nodeclass="SceneDefault",
             inputs = (dict(name='Key', interface=IStr),
                       dict(name='Value', interface=None),),
             outputs = (dict(name='Obj', interface=None),),
             lazy = False,
             )

__all__.append('scene_rw')


    

