# -*-python-*-
import os, re

Import("env")

# 1. Select and install the headers

includes = env.ALEAGlob('*.h', dir='.')
env.ALEAIncludes("openalea_meta", includes)

# Build shared libraries

# 1. If you have only one shared library:
# sources = env.ALEAGlob('*.cpp')

# 2. Build first library
sources = "dummy.cpp"
target = "dummy"

# Add defines to export symbols on Windows
DEFINES = list(env['CPPDEFINES'])
DEFINES.append('SCENEOBJ_DLL')

# Build the library
lib1 = env.ALEALibrary(target, sources, CPPDEFINES=DEFINES)


