
# This file has been generated at Fri Aug 27 18:18:05 2010

from openalea.core import *


__name__ = 'openalea.misc.test'

__editable__ = True
__description__ = 'tests on misc package nodes'
__license__ = 'CECILL-C'
__url__ = 'http://openalea.gforge.inria.fr'
__alias__ = []
__version__ = '0.0.1'
__authors__ = 'Thomas Cokelaer'
__institutes__ = 'INRIA/CIRAD'
__icon__ = ''


__all__ = ['_194038668']



_194038668 = CompositeNodeFactory(name='shared_data_browser',
                             description='author: Thomas Cokelaer',
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.flow control', 'annotation'),
   3: ('openalea.data structure.list', 'list'),
   4: ('openalea.data structure.string', 'string'),
   6: ('vplants.stats', 'Histogram'),
   7: ('vplants.stats', 'Plot (stat_tool)'),
   8: ('openalea.data structure.string', 'string'),
   9: ('openalea.misc', 'SharedDataBrowser')},
                             elt_connections={  167402984: (6, 0, 7, 0),
   167402996: (3, 0, 9, 0),
   167403008: (4, 0, 9, 2),
   167403020: (9, 0, 6, 0)},
                             elt_data={  2: {  'factory': '<openalea.core.node.NodeFactory object at 0xba2962c> : "annotation"',
         'id': 2,
         'posx': -253.0,
         'posy': -202.0,
         'txt': u'Usage of shared_data_browser node (non interactive)\n 1 - connect either a string or a list with one element, \n  which contains the package name (e.g., stat_tool) \n  without the namespace.\n  2 - connect the filename string.\n  3 - Run the dataflow.'},
   3: {  'block': False,
         'caption': 'list',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb0cc10c> : "list"',
         'hide': True,
         'id': 3,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -64.935876743063474,
         'posy': 38.09053259219187,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': "'meri1.his'",
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb519f2c> : "string"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 42.378407270482995,
         'posy': 31.939264954929385,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'Histogram',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb5edf6c> : "Histogram"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -81.371220664827618,
         'posy': 191.87506664691685,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'Plot (stat_tool)',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb5ed28c> : "Plot (stat_tool)"',
         'hide': True,
         'id': 7,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -80.724706106265145,
         'posy': 268.99388491954221,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': "'stat_tool'",
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xb519f2c> : "string"',
         'hide': True,
         'id': 8,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -186.769510752467,
         'posy': 35.442486922675258,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'SharedDataBrowser',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0xba281ec> : "SharedDataBrowser"',
         'hide': True,
         'id': 9,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -113.16434430766827,
         'posy': 119.22671989557908,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [],
   3: [(0, "['stat_tool']")],
   4: [(0, "'meri1.his'")],
   6: [],
   7: [(1, '0'), (2, "''"), (3, "'v'")],
   8: [(0, "'stat_tool'")],
   9: [(1, "'*'")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'color': None,
         'position': [-253.0, -202.0],
         'rectP2': (557.63278215121977, 533.48905173615049),
         'text': u'Usage of shared_data_browser node (non interactive)\n 1 - connect either a string or a list with one element, \n  which contains the package name (e.g., stat_tool) \n  without the namespace.\n  2 - connect the filename string.\n  3 - Run the dataflow.',
         'textColor': None},
   3: {  'position': [-64.935876743063474, 38.09053259219187],
         'useUserColor': False,
         'userColor': None},
   4: {  'position': [42.378407270482995, 31.939264954929385],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-229.23554663087168, 39.579430412954935],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [-81.371220664827618, 191.87506664691685],
         'useUserColor': False,
         'userColor': None},
   7: {  'position': [-80.724706106265145, 268.99388491954221],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [-186.769510752467, 35.442486922675258],
         'useUserColor': False,
         'userColor': None},
   9: {  'position': [-113.16434430766827, 119.22671989557908],
         'useUserColor': False,
         'userColor': None},
   '__in__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




