
# This file has been generated at Tue Nov 03 18:24:08 2009

from openalea.core import *


__name__ = 'openalea.scheduler.example'

__editable__ = True
__description__ = 'Scheduler example.'
__license__ = 'Cecill-C'
__url__ = 'http://openalea.gforge.inria.fr'
__alias__ = []
__version__ = '0.8.0'
__authors__ = 'Jerome Chopard, Christophe Pradal'
__institutes__ = 'INRIA/CIRAD'
__icon__ = ''


__all__ = ['_80093488']



_80093488 = CompositeNodeFactory(name='1. Two processes',
                             description='Test the scheduler in openalea',
                             category='simulation',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.math', 'random'),
   3: ('openalea.math', 'randint'),
   4: ('openalea.python method', 'print'),
   5: ('openalea.python method', 'print'),
   6: ('openalea.flow control', 'rendez vous'),
   7: ('openalea.flow control', 'rendez vous'),
   8: ('openalea.scheduler', 'task'),
   9: ('openalea.scheduler', 'task'),
   10: ('openalea.flow control', 'X'),
   11: ('openalea.flow control', 'X'),
   12: ('openalea.scheduler', 'scheduler'),
   13: ('openalea.scheduler', 'run'),
   14: ('openalea.data structure', 'int'),
   15: ('openalea.data structure', 'int')},
                             elt_connections={  9926476: (15, 0, 8, 1),
   9926488: (14, 0, 9, 1),
   9926500: (11, 0, 6, 1),
   9926512: (12, 0, 13, 0),
   9926524: (2, 0, 4, 0),
   9926536: (7, 0, 9, 0),
   9926548: (4, 0, 7, 0),
   9926560: (5, 0, 6, 0),
   9926572: (10, 0, 7, 1),
   9926584: (9, 0, 12, 0),
   9926596: (8, 0, 12, 0),
   9926608: (3, 0, 5, 0),
   9926620: (6, 0, 8, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'random',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 30.0,
         'posy': 20.0,
         'priority': 0,
         'user_application': None},
   3: {  'block': False,
         'caption': 'randint',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 320.0,
         'posy': 13.75,
         'priority': 0,
         'user_application': None},
   4: {  'block': False,
         'caption': 'print',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 45.0,
         'posy': 76.25,
         'priority': 0,
         'user_application': False},
   5: {  'block': False,
         'caption': 'print',
         'hide': True,
         'lazy': False,
         'port_hide_changed': set(),
         'posx': 323.75,
         'posy': 67.5,
         'priority': 0,
         'user_application': None},
   6: {  'block': False,
         'caption': 'rendez vous',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 335.0,
         'posy': 130.0,
         'priority': 0,
         'user_application': None},
   7: {  'block': False,
         'caption': 'rendez vous',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 60.0,
         'posy': 138.75,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'task',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 392.5,
         'posy': 188.75,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'task',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 73.75,
         'posy': 202.5,
         'priority': 0,
         'user_application': None},
   10: {  'block': False,
          'caption': 'X0',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 112.5,
          'posy': 83.75,
          'priority': 0,
          'user_application': None},
   11: {  'block': False,
          'caption': 'X1',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 390.0,
          'posy': 66.25,
          'priority': 0,
          'user_application': None},
   12: {  'block': False,
          'caption': 'scheduler',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 256.25,
          'posy': 263.75,
          'priority': 0,
          'user_application': None},
   13: {  'block': False,
          'caption': 'run',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 288.75,
          'posy': 333.75,
          'priority': 0,
          'user_application': None},
   14: {  'block': False,
          'caption': '0',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 200.0,
          'posy': 131.25,
          'priority': 0,
          'user_application': None},
   15: {  'block': False,
          'caption': '0',
          'hide': True,
          'lazy': True,
          'port_hide_changed': set(),
          'posx': 490.0,
          'posy': 117.5,
          'priority': 0,
          'user_application': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0,
                'user_application': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0,
                 'user_application': None}},
                             elt_value={  2: [],
   3: [(0, '0'), (1, '100')],
   4: [],
   5: [],
   6: [],
   7: [],
   8: [(2, '0'), (3, "''"), (4, '0')],
   9: [(2, '0'), (3, "''"), (4, '0')],
   10: [(0, "'x'")],
   11: [(0, "'x'")],
   12: [],
   13: [(1, '16')],
   14: [(0, '1')],
   15: [(0, '4')],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




