# -*-python-*-

import os
from openalea.sconsx import config, environ


ALEASolution = config.ALEASolution

pj = os.path.join

name = 'openalea_meta'

SConsignFile()


options = Options(['../options.py', 'options.py'], ARGUMENTS)
tools = []

env = ALEASolution(options, tools)

# Set build directory
prefix = env['build_prefix']

# Build stage
SConscript(pj(prefix,"src/cpp/SConscript"), exports="env")

Default("build")
