
# This file has been generated at Thu Jan 31 18:50:20 2008

from openalea.core.external import *


__name__ = 'openalea.tutorial.functional'

__editable__ = True
__version__ = ''
__description__ = ''
__license__ = ''
__authors__ = ''
__url__ = ''
__institutes__ = ''
 

__all__ = ['_173141592', 'Tut3', 'TutOrder', 'Fibonacci', 'str', 'Tut1', 'TutWhile', 'Tut2', 'Tut4', '_168048064']



_173141592 = CompositeNodeFactory(name='multi_file', 
                             description='', 
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('catalog.functional', 'map'),
   3: ('system', 'annotation'),
   4: ('catalog.file', 'glob'),
   5: ('catalog.file', 'dirname'),
   6: ('system', 'annotation'),
   7: ('catalog.data', 'string'),
   8: ('catalog.file', 'joinpath'),
   9: ('catalog.string', 'join'),
   10: ('catalog.data', 'string'),
   11: ('openalea.system', 'os.system'),
   12: ('system', 'X'),
   13: ('system', 'annotation')},
                             elt_connections={  159395648: (11, 0, 2, 0),
   159395660: (9, 0, 11, 0),
   159395672: (12, 0, 9, 0),
   159395684: (10, 0, 9, 0),
   159395696: (4, 0, 2, 1),
   159395708: (8, 0, 4, 0),
   159395720: (5, 0, 8, 0),
   159395732: (7, 0, 8, 0)},
                             elt_data={  2: {  'caption': 'map',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 266.02157943067033,
         'posy': 287.39784205693297,
         'priority': 0},
   3: {'posx': 103.75, 'posy': 38.75, 'txt': 'Build command'},
   4: {  'caption': 'glob',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 396.25,
         'posy': 211.25,
         'priority': 0},
   5: {  'caption': 'dirname',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 346.25,
         'posy': 73.75,
         'priority': 0},
   6: {'posx': 370.0, 'posy': 17.5, 'txt': 'Get a list of file'},
   7: {  'caption': "'*.py'",
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 460.0,
         'posy': 73.75,
         'priority': 0},
   8: {  'caption': 'joinpath',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 386.25,
         'posy': 150.0,
         'priority': 0},
   9: {  'caption': 'join',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 157.5,
         'posy': 150.0,
         'priority': 0},
   10: {  'caption': "'dos2unix'",
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 82.5,
          'posy': 78.75,
          'priority': 0},
   11: {  'caption': 'os.system',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 137.5,
          'posy': 218.75,
          'priority': 0},
   12: {  'caption': 'Filename',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 208.10146923783287,
          'posy': 72.674471992653793,
          'priority': 0},
   13: {'posx': 162.5, 'posy': 340.0, 'txt': 'Apply the command to each file'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [],
   3: [],
   4: [],
   5: [(0, "'/home/sdufour/pydrop/src/pydrop/'")],
   6: [],
   7: [(0, "'*.py'")],
   8: [],
   9: [(1, "' '")],
   10: [(0, "'dos2unix'")],
   11: [],
   12: [(0, "'x'")],
   13: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




Tut3 = CompositeNodeFactory(name='Tut3', 
                             description='', 
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('Catalog.Python', 'range'),
   3: ('System', 'annotation'),
   4: ('Catalog.Math', '>='),
   5: ('Catalog.Math', 'and'),
   6: ('Catalog.Math', '>='),
   7: ('System', 'X'),
   8: ('Catalog.Data', 'int'),
   9: ('Catalog.Data', 'int'),
   10: ('Catalog.Functional', 'filter')},
                             elt_connections={  160452416: (9, 0, 4, 0),
   160452428: (7, 0, 4, 1),
   160452440: (2, 0, 10, 1),
   160452452: (6, 0, 5, 1),
   160452464: (8, 0, 6, 1),
   160452476: (5, 0, 10, 0),
   160452488: (4, 0, 5, 0),
   160452500: (7, 0, 6, 0)},
                             elt_data={  2: {  'caption': 'range',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 493.75,
         'posy': 230.0,
         'priority': 0},
   3: {'posx': 363.75, 'posy': 80.0, 'txt': 'X <= 7 and X >= 2'},
   4: {  'caption': '>=',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 143.75,
         'posy': 212.5,
         'priority': 0},
   5: {  'caption': 'and',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 233.75,
         'posy': 307.5,
         'priority': 0},
   6: {  'caption': '>=',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 266.25,
         'posy': 215.0,
         'priority': 0},
   7: {  'caption': 'X',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 202.5,
         'posy': 93.75,
         'priority': 0},
   8: {  'caption': '2',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 297.5,
         'posy': 118.75,
         'priority': 0},
   9: {  'caption': '7',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 113.75,
         'posy': 133.75,
         'priority': 0},
   10: {  'caption': 'filter',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 345.67901234567898,
          'posy': 376.54320987654313,
          'priority': 0},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(0, '0'), (1, '10'), (2, '1')],
   3: [],
   4: [],
   5: [],
   6: [],
   7: [(0, "'x'")],
   8: [(0, '2')],
   9: [(0, '7')],
   10: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




TutOrder = CompositeNodeFactory(name='TutOrder', 
                             description='', 
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('Catalog.Data', 'float'),
   3: ('Catalog.Data', 'float'),
   4: ('Catalog.Data', 'list'),
   5: ('Catalog.Data', 'float'),
   6: ('System', 'annotation'),
   7: ('System', 'annotation')},
                             elt_connections={154472316: (5, 0, 4, 0), 154472328: (3, 0, 4, 0), 154472340: (2, 0, 4, 0)},
                             elt_data={  2: {  'caption': '2.0',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 212.5,
         'posy': 133.75,
         'priority': 0},
   3: {  'caption': '1.0',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 116.25,
         'posy': 136.25,
         'priority': 0},
   4: {  'caption': 'list',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 217.5,
         'posy': 278.75,
         'priority': 0},
   5: {  'caption': '3.0',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 300.0,
         'posy': 135.0,
         'priority': 0},
   6: {'posx': 311.25, 'posy': 288.75, 'txt': '[1.0, 2.0, 3.0]'},
   7: {  'posx': 87.5,
         'posy': 67.5,
         'txt': 'Create a list with multiple connections'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(0, '2.0')],
   3: [(0, '1.0')],
   4: [],
   5: [(0, '3.0')],
   6: [],
   7: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




Fibonacci = CompositeNodeFactory(name='Fibonacci', 
                             description='', 
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('system', 'X'),
   3: ('system', 'X'),
   4: ('catalog.data', 'int'),
   5: ('catalog.data', 'int'),
   6: ('catalog.data', 'int'),
   7: ('Catalog.Math', '>='),
   8: ('system', 'while multivariate'),
   9: ('Catalog.Math', '+'),
   10: ('catalog.python', 'getitem'),
   11: ('catalog.data', 'int'),
   12: ('system', 'annotation'),
   13: ('system', 'annotation'),
   14: ('system', 'annotation'),
   15: ('system', 'annotation'),
   16: ('system', 'annotation')},
                             elt_connections={  149524240: (2, 0, 10, 0),
   149524252: (6, 0, 7, 0),
   149524264: (9, 0, 8, 2),
   149524276: (2, 0, 7, 1),
   149524288: (2, 0, 9, 0),
   149524300: (3, 0, 10, 0),
   149524312: (7, 0, 8, 1),
   149524324: (3, 0, 9, 1),
   149524336: (11, 0, 10, 1),
   149524348: (4, 0, 8, 0),
   149524360: (10, 0, 8, 2),
   149524372: (5, 0, 8, 0)},
                             elt_data={  2: {  'caption': 'Un',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 449.27240242339576,
         'posy': 105.79273533774301,
         'priority': 0},
   3: {  'caption': 'Un+1',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 534.71298685236536,
         'posy': 102.0978083913642,
         'priority': 0},
   4: {  'caption': '1',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 77.962297016015754,
         'posy': 246.54707785515222,
         'priority': 0},
   5: {  'caption': '1',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 125.46229701601575,
         'posy': 244.04707785515222,
         'priority': 0},
   6: {  'caption': '10000000',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 252.15791379874412,
         'posy': 145.68258923050064,
         'priority': 0},
   7: {  'caption': '>=',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 276.23835212047129,
         'posy': 249.15722396239465,
         'priority': 0},
   8: {  'caption': 'while multivariate',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 251.56879044219841,
         'posy': 366.97098205083438,
         'priority': 0},
   9: {  'caption': '+',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 566.56879044219841,
         'posy': 261.21663953342511,
         'priority': 0},
   10: {  'caption': 'getitem',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 381.78908265668321,
          'posy': 266.71229701601584,
          'priority': 0},
   11: {  'caption': '1',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 467.26805990598655,
          'posy': 220.18693174790988,
          'priority': 0},
   12: {  'posx': 273.94196410166859,
          'posy': 41.894196410166884,
          'txt': 'Fibonacci'},
   13: {  'posx': 561.51371738857722,
          'posy': 337.57678564066754,
          'txt': 'Un+1 <- Un + Un+1'},
   14: {  'posx': 419.01371738857728,
          'posy': 337.57678564066748,
          'txt': 'Un <- Un+1'},
   15: {  'posx': 96.78908265668332,
          'posy': 204.33250783077585,
          'txt': 'initial value'},
   16: {  'posx': 240.18031622213999,
          'posy': 108.73835212047138,
          'txt': 'max value'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(0, "'x'")],
   3: [(0, "'Un+1'")],
   4: [(0, '1')],
   5: [(0, '1')],
   6: [(0, '10000000')],
   7: [],
   8: [  (0, '[1, 1, []]'),
         (  2,
            '[<openalea.core.dataflow.SubDataflow object at 0x97eed6c>, <openalea.core.dataflow.SubDataflow object at 0x97eee0c>, <openalea.core.dataflow.SubDataflow object at 0x97eee2c>]')],
   9: [],
   10: [],
   11: [(0, '1')],
   12: [],
   13: [],
   14: [],
   15: [],
   16: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




str = CompositeNodeFactory(name='str', 
                             description='', 
                             category='Unclassified',
                             doc='',
                             inputs=[{'interface': IStr, 'name': 'String', 'value': ''}],
                             outputs=[{'interface': IStr, 'name': 'String'}],
                             elt_factory={4: ('Catalog.Data', 'string')},
                             elt_connections={168864740: ('__in__', 0, 4, 0), 168864780: (4, 0, '__out__', 0)},
                             elt_data={  4: {  'caption': "''",
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 112.5,
         'posy': 126.25,
         'priority': 0}},
                             elt_value={4: []},
                             lazy=True,
                             )




Tut1 = CompositeNodeFactory(name='Tut1', 
                             description='', 
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('Catalog.Python', 'range'),
   3: ('Catalog.Functional', 'map'),
   4: ('Catalog.Math', '+'),
   7: ('System', 'X'),
   8: ('Catalog.Data', 'int'),
   9: ('Catalog.Math', '*')},
                             elt_connections={  139960152: (4, 0, 9, 0),
   139960164: (2, 0, 3, 1),
   139960176: (8, 0, 4, 1),
   139960188: (9, 0, 3, 0),
   139960200: (7, 0, 4, 0),
   139960212: (8, 0, 9, 1)},
                             elt_data={  2: {  'caption': 'range',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 366.25,
         'posy': 145.0,
         'priority': 0},
   3: {  'caption': 'map',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 220.0,
         'posy': 297.5,
         'priority': 0},
   4: {  'caption': '+',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 98.75,
         'posy': 138.75,
         'priority': 0},
   7: {  'caption': 'X',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 50.0,
         'posy': 36.25,
         'priority': 0},
   8: {  'caption': '5',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 172.5,
         'posy': 47.5,
         'priority': 0},
   9: {  'caption': '*',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 131.25,
         'posy': 206.25,
         'priority': 0},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(0, '0'), (1, '10'), (2, '1')],
   3: [],
   4: [],
   7: [(0, "'x'")],
   8: [(0, '5')],
   9: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




TutWhile = CompositeNodeFactory(name='TutWhile', 
                             description='', 
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('System', 'X'),
   3: ('System', 'while univariate'),
   4: ('Catalog.Math', '>='),
   5: ('Catalog.Data', 'int'),
   6: ('Catalog.Data', 'int'),
   7: ('Catalog.Math', '+'),
   8: ('Catalog.Data', 'int'),
   9: ('System', 'while multivariate'),
   10: ('Catalog.Data', 'list'),
   11: ('System', 'X'),
   12: ('System', 'X'),
   13: ('Catalog.Math', '*'),
   14: ('Catalog.Math', '>='),
   15: ('Catalog.Data', 'int'),
   16: ('Catalog.Math', '+'),
   17: ('Catalog.Data', 'int'),
   18: ('System', 'annotation'),
   19: ('System', 'annotation'),
   25: ('System', 'annotation'),
   26: ('System', 'annotation'),
   27: ('System', 'annotation'),
   28: ('System', 'annotation'),
   29: ('System', 'annotation'),
   30: ('System', 'annotation')},
                             elt_connections={  148664020: (5, 0, 4, 0),
   148664032: (12, 0, 14, 1),
   148664044: (16, 0, 9, 2),
   148664056: (12, 0, 13, 1),
   148664068: (11, 0, 13, 0),
   148664080: (7, 0, 3, 2),
   148664092: (12, 0, 16, 0),
   148664104: (4, 0, 3, 1),
   148664116: (2, 0, 7, 0),
   148664128: (13, 0, 9, 2),
   148664140: (10, 0, 9, 0),
   148664152: (17, 0, 14, 0),
   148664164: (2, 0, 4, 1),
   148664176: (8, 0, 3, 0),
   148664188: (15, 0, 16, 1),
   148664200: (14, 0, 9, 1),
   148664212: (6, 0, 7, 1)},
                             elt_data={  2: {  'caption': 'X',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 335.0,
         'posy': 118.75,
         'priority': 0},
   3: {  'caption': 'while univariate',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 293.04420896720154,
         'posy': 356.12805978134344,
         'priority': 0},
   4: {  'caption': '>=',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 298.75,
         'posy': 217.5,
         'priority': 0},
   5: {  'caption': '10',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 241.25,
         'posy': 150.0,
         'priority': 0},
   6: {  'caption': '3',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 475.0,
         'posy': 176.25,
         'priority': 0},
   7: {  'caption': '+',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 432.66158206559697,
         'posy': 251.59298505466415,
         'priority': 0},
   8: {  'caption': '0',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 216.25,
         'posy': 247.5,
         'priority': 0},
   9: {  'caption': 'while multivariate',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 311.81704456850707,
         'posy': 719.59755217492523,
         'priority': 0},
   10: {  'caption': 'list',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 169.31704456850707,
          'posy': 599.59755217492523,
          'priority': 0},
   11: {  'caption': 'X',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 410.56704456850707,
          'posy': 493.34755217492523,
          'priority': 0},
   12: {  'caption': 'T',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 529.88408913701414,
          'posy': 486.00913424052226,
          'priority': 0},
   13: {  'caption': '*',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 465.38564157943983,
          'posy': 609.59755217492523,
          'priority': 0},
   14: {  'caption': '>=',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 315.56704456850707,
          'posy': 595.84755217492523,
          'priority': 0},
   15: {  'caption': '1',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 733.32773125145502,
          'posy': 585.1219402186565,
          'priority': 0},
   16: {  'caption': '+',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 640.61393518332409,
          'posy': 656.98599263388542,
          'priority': 0},
   17: {  'caption': '10',
          'hide': True,
          'lazy': True,
          'minimal': False,
          'port_hide_changed': set([]),
          'posx': 271.81704456850707,
          'posy': 530.84755217492523,
          'priority': 0},
   18: {  'posx': 302.02603069317337,
          'posy': 67.275940486157111,
          'txt': 'Condition'},
   19: {  'posx': 111.64943314723948,
          'posy': 246.20131411955367,
          'txt': 'init value'},
   25: {  'posx': 691.30818094903373,
          'posy': 194.61134374272481,
          'txt': 'x = 0\nwhile x <=10 :\n   x += 3'},
   26: {  'posx': 853.11618148403488,
          'posy': 552.52155377992858,
          'txt': 'x,t = 0, 0\n\nwhile t <=10 :\n   x = x * t\n   t += 1'},
   27: {  'posx': 548.16788204231648,
          'posy': 729.95606165384731,
          'txt': 'Functions'},
   28: {  'posx': 224.67080651313552,
          'posy': 480.89194155615934,
          'txt': 'Condition'},
   29: {  'posx': 45.745432879739013,
          'posy': 599.69838964873452,
          'txt': 'init values'},
   30: {  'posx': 525.32489698765232,
          'posy': 247.63271710862085,
          'txt': 'Function'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(0, "'x'")],
   3: [],
   4: [],
   5: [(0, '10')],
   6: [(0, '3')],
   7: [],
   8: [(0, '0')],
   9: [],
   10: [(0, '[1, 1]')],
   11: [(0, "'x'")],
   12: [(0, "'x'")],
   13: [],
   14: [],
   15: [(0, '1')],
   16: [],
   17: [(0, '10')],
   18: [],
   19: [],
   25: [],
   26: [],
   27: [],
   28: [],
   29: [],
   30: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




Tut2 = CompositeNodeFactory(name='Tut2', 
                             description='', 
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('Catalog.Functional', 'reduce'),
   3: ('System', 'X'),
   4: ('System', 'X'),
   5: ('Catalog.Math', '*'),
   6: ('Catalog.Python', 'range'),
   7: ('System', 'annotation')},
                             elt_connections={  154472304: (5, 0, 2, 0),
   154472316: (3, 0, 5, 0),
   154472328: (4, 0, 5, 1),
   154472340: (6, 0, 2, 1)},
                             elt_data={  2: {  'caption': 'reduce',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 340.0,
         'posy': 370.0,
         'priority': 0},
   3: {  'caption': 'X0',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 296.25,
         'posy': 183.75,
         'priority': 0},
   4: {  'caption': 'X1',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 385.0,
         'posy': 181.25,
         'priority': 0},
   5: {  'caption': '*',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 335.0,
         'posy': 255.0,
         'priority': 0},
   6: {  'caption': 'range',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 463.75,
         'posy': 263.75,
         'priority': 0},
   7: {'posx': 440.0, 'posy': 372.5, 'txt': 'Factorial with a reduce'},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [],
   3: [(0, "'x1'")],
   4: [(0, "'x1'")],
   5: [],
   6: [(0, '1'), (1, '10'), (2, '1')],
   7: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




Tut4 = CompositeNodeFactory(name='Tut4', 
                             description='', 
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('Catalog.Data', 'list'),
   3: ('Catalog.Functional', 'map'),
   4: ('System', 'X'),
   6: ('Catalog.Math', '>='),
   7: ('System', 'X'),
   8: ('Catalog.Data', 'int'),
   9: ('Catalog.Functional', 'filter')},
                             elt_connections={  145370968: (8, 0, 6, 1),
   145370980: (2, 0, 3, 1),
   145370992: (4, 0, 9, 1),
   145371004: (7, 0, 6, 0),
   145371016: (9, 0, 3, 0),
   145371028: (6, 0, 9, 0)},
                             elt_data={  2: {  'caption': 'list',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 433.75,
         'posy': 286.25,
         'priority': 0},
   3: {  'caption': 'map',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 345.0,
         'posy': 368.75,
         'priority': 0},
   4: {  'caption': 'X',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 376.25,
         'posy': 172.5,
         'priority': 0},
   6: {  'caption': '>=',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 266.25,
         'posy': 215.0,
         'priority': 0},
   7: {  'caption': 'X',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 175.0,
         'posy': 107.5,
         'priority': 0},
   8: {  'caption': '7',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 297.5,
         'posy': 118.75,
         'priority': 0},
   9: {  'caption': 'filter',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 290.0,
         'posy': 278.75,
         'priority': 0},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [  (  0,
            '[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]]')],
   3: [],
   4: [(0, "'x'")],
   6: [],
   7: [(0, "'x'")],
   8: [(0, '7')],
   9: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




_168048064 = CompositeNodeFactory(name='test_str', 
                             description='', 
                             category='Unclassified',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('Catalog.Data', 'string'),
   3: ('Catalog.Data', 'string'),
   5: ('Catalog.Functional', 'map'),
   6: ('System', 'X'),
   7: ('TestLambda', 'str')},
                             elt_connections={  164581232: (3, 0, 5, 1),
   164581244: (2, 0, 5, 1),
   164581256: (6, 0, 7, 0),
   164581268: (7, 0, 5, 0)},
                             elt_data={  2: {  'caption': "'toto'",
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 253.75,
         'posy': 121.25,
         'priority': 0},
   3: {  'caption': "'toto'",
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 382.5,
         'posy': 183.75,
         'priority': 0},
   5: {  'caption': 'map',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 135.0,
         'posy': 233.75,
         'priority': 0},
   6: {  'caption': 'X0',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 205.0,
         'posy': 31.25,
         'priority': 0},
   7: {  'caption': 'str',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set([]),
         'posx': 112.5,
         'posy': 126.25,
         'priority': 0},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set([]),
                'posx': 20.0,
                'posy': 5.0,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set([]),
                 'posx': 20.0,
                 'posy': 250.0,
                 'priority': 0}},
                             elt_value={  2: [(0, "'toto'")],
   3: [(0, "'toto'")],
   5: [],
   6: [(0, "'x'")],
   7: [],
   '__in__': [],
   '__out__': []},
                             lazy=True,
                             )




