
# This file has been generated at Fri Mar 26 15:22:42 2010

from openalea.core import *


__name__ = 'openalea.numpy.test.creation'

__editable__ = True
__description__ = 'numpy test nodes.'
__license__ = 'CECILL-C'
__url__ = 'http://openalea.gforge.inria.fr/doc/openalea/numpy/doc/_build/html/contents.html'
__alias__ = []
__version__ = '0.8.0'
__authors__ = 'Eric MOSCARDI'
__institutes__ = 'INRIA/CIRAD'
__icon__ = 'icon.png'


__all__ = ['_4746986384', '_4703145872']



_4746986384 = CompositeNodeFactory(name='numpy.tri',
                             description='Examples',
                             category='numpy',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.numpy.creation', 'tri'), 3: ('openalea.numpy.creation', 'tri')},
                             elt_connections={  },
                             elt_data={  2: {  'block': False,
         'caption': 'tri',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -688.0,
         'posy': -236.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'tri',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -796.0,
         'posy': -237.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '3'), (1, '5'), (2, '-1'), (3, "'float64'")],
   3: [(0, '3'), (1, '5'), (2, '2'), (3, "'int8'")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-688.0, -236.0], 'userColor': None, 'useUserColor': False},
   3: {'position': [-796.0, -237.0], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             )




_4703145872 = CompositeNodeFactory(name='numpy.eye',
                             description='Examples',
                             category='numpy',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.numpy.creation', 'eye'), 3: ('openalea.numpy.creation', 'eye')},
                             elt_connections={  },
                             elt_data={  2: {  'block': False,
         'caption': 'eye',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -829.82126676362464,
         'posy': -227.01787332363753,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'eye',
         'hide': True,
         'is_in_error_state': False,
         'is_user_application': False,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -729.83914008726208,
         'posy': -226.01787332363756,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'hide': True,
                'is_in_error_state': False,
                'is_user_application': False,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'hide': True,
                 'is_in_error_state': False,
                 'is_user_application': False,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '2'), (1, 'None'), (2, '0'), (3, "'int8'")],
   3: [(0, '3'), (1, 'None'), (2, '1'), (3, "'float64'")],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-829.82126676362464, -227.01787332363753],
         'useUserColor': False,
         'userColor': None},
   3: {  'position': [-729.83914008726208, -226.01787332363756],
         'useUserColor': False,
         'userColor': None},
   '__in__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             )




