
# This file has been generated at Mon Sep  6 12:12:39 2010

from openalea.core import *


__name__ = 'openalea.numpy.demo'

__editable__ = True
__description__ = 'numpy nodes.'
__license__ = 'CECILL-C'
__url__ = 'http://openalea.gforge.inria.fr/doc/openalea/numpy/doc/_build/html/contents.html'
__alias__ = []
__version__ = '0.8.0'
__authors__ = 'Eric MOSCARDI'
__institutes__ = 'INRIA/CIRAD'
__icon__ = 'icon.png'


__all__ = ['_5005745296', '_4981932432']



_5005745296 = CompositeNodeFactory(name='creation of two dimensional array',
                             description='Creation of two dimensional array and get of these properties',
                             category='numpy',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.numpy.creation', 'array'),
   3: ('openalea.data structure.list', 'list'),
   4: ('openalea.numpy.infos', 'ndim'),
   5: ('openalea.numpy.infos', 'shape'),
   6: ('openalea.numpy.infos', 'dtype'),
   7: ('openalea.numpy.infos', 'itemsize')},
                             elt_connections={  4297110208: (2, 0, 7, 0),
   4297110232: (2, 0, 6, 0),
   4297110256: (2, 0, 5, 0),
   4297110280: (2, 0, 4, 0),
   4297110304: (3, 0, 2, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'array',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x128e03c90> : "array"',
         'hide': True,
         'id': 2,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -569.97322483814833,
         'posy': -21.496113928672312,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'list',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x10120bd90> : "list"',
         'hide': True,
         'id': 3,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -607.1703903388244,
         'posy': -85.555388524075241,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'ndim',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x128e29c90> : "ndim"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -592.35581898226076,
         'posy': 39.109545912033539,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'shape',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x128e29e10> : "shape"',
         'hide': True,
         'id': 5,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -539.18441386590064,
         'posy': 39.109545912033539,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'dtype',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x128e29e90> : "dtype"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -482.49754394845871,
         'posy': 39.109545912033539,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'itemsize',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x128e31110> : "itemsize"',
         'hide': True,
         'id': 7,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -425.37124093088153,
         'posy': 39.109545912033539,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(1, "'float64'"), (2, 'True'), (3, "'C'"), (4, 'False'), (5, '0')],
   3: [(0, '[(1.5, 2, 3), (4, 5, 6)]')],
   4: [],
   5: [],
   6: [],
   7: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {'position': [-569.97322483814833, -21.496113928672312], 'userColor': None, 'useUserColor': False},
   3: {'position': [-607.1703903388244, -85.555388524075241], 'userColor': None, 'useUserColor': False},
   4: {'position': [-592.35581898226076, 39.109545912033539], 'userColor': None, 'useUserColor': False},
   5: {'position': [-539.18441386590064, 39.109545912033539], 'userColor': None, 'useUserColor': False},
   6: {'position': [-482.49754394845871, 39.109545912033539], 'userColor': None, 'useUserColor': False},
   7: {'position': [-425.37124093088153, 39.109545912033539], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [0, 0], 'userColor': None, 'useUserColor': True},
   '__out__': {'position': [0, 0], 'userColor': None, 'useUserColor': True}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




_4981932432 = CompositeNodeFactory(name='simple creation of array',
                             description='A basic example of creation of an array and get of these properties',
                             category='numpy',
                             doc='',
                             inputs=[],
                             outputs=[],
                             elt_factory={  2: ('openalea.numpy.creation', 'arange'),
   3: ('openalea.numpy.manipulation', 'reshape'),
   4: ('openalea.numpy.infos', 'shape'),
   5: ('openalea.numpy.infos', 'dtype'),
   6: ('openalea.numpy.infos', 'itemsize'),
   7: ('openalea.numpy.infos', 'ndim'),
   8: ('openalea.numpy.infos', 'size'),
   9: ('openalea.flow control', 'annotation'),
   10: ('openalea.flow control', 'annotation')},
                             elt_connections={  4297110184: (3, 0, 6, 0),
   4297110208: (3, 0, 5, 0),
   4297110232: (3, 0, 8, 0),
   4297110256: (3, 0, 7, 0),
   4297110280: (3, 0, 4, 0),
   4297110304: (2, 0, 3, 0)},
                             elt_data={  2: {  'block': False,
         'caption': 'arange',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x12cac9150> : "arange"',
         'hide': True,
         'id': 2,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -939.0,
         'posy': -443.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   3: {  'block': False,
         'caption': 'reshape',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x128bebc50> : "reshape"',
         'hide': True,
         'id': 3,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -891.0,
         'posy': -382.0,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   4: {  'block': False,
         'caption': 'shape',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x128beb510> : "shape"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -956.0,
         'posy': -282.99999999999994,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'dtype',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x129b883d0> : "dtype"',
         'hide': True,
         'id': 5,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -774.0,
         'posy': -282.99999999999994,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'itemsize',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x129b88090> : "itemsize"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -709.0,
         'posy': -282.99999999999994,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'ndim',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x128beb910> : "ndim"',
         'hide': True,
         'id': 7,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -887.0,
         'posy': -282.99999999999994,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'size',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x1296f81d0> : "size"',
         'hide': True,
         'id': 8,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': -825.0,
         'posy': -282.99999999999994,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'factory': '<openalea.core.node.NodeFactory object at 0x1168d8b10> : "annotation"',
         'id': 9,
         'posx': -945.0,
         'posy': -489.0,
         'txt': u'simple creation of an array'},
   10: {  'factory': '<openalea.core.node.NodeFactory object at 0x1168d8b10> : "annotation"',
          'id': 10,
          'posx': -1022.0,
          'posy': -318.0,
          'txt': u'properties'},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'port_hide_changed': set(),
                'posx': 0,
                'posy': 0,
                'priority': 0,
                'use_user_color': True,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'port_hide_changed': set(),
                 'posx': 0,
                 'posy': 0,
                 'priority': 0,
                 'use_user_color': True,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  2: [(0, '0'), (1, '10.0'), (2, '1'), (3, "'float64'")],
   3: [(1, '(2, 5)'), (2, "'C'")],
   4: [],
   5: [],
   6: [],
   7: [],
   8: [],
   9: [],
   10: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  2: {  'position': [-939.0, -443.0], 'useUserColor': False, 'userColor': None},
   3: {  'position': [-891.0, -382.0], 'useUserColor': False, 'userColor': None},
   4: {  'position': [-956.0, -282.99999999999994],
         'useUserColor': False,
         'userColor': None},
   5: {  'position': [-774.0, -282.99999999999994],
         'useUserColor': False,
         'userColor': None},
   6: {  'position': [-709.0, -282.99999999999994],
         'useUserColor': False,
         'userColor': None},
   7: {  'position': [-887.0, -282.99999999999994],
         'useUserColor': False,
         'userColor': None},
   8: {  'position': [-825.0, -282.99999999999994],
         'useUserColor': False,
         'userColor': None},
   9: {  'color': None,
         'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">simple creation of an array</p></body></html>',
         'position': [-945.0, -489.0],
         'rectP2': (226.625, 146.5),
         'text': u'simple creation of an array'},
   10: {  'color': None,
          'htmlText': u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n<html><head><meta name="qrichtext" content="1" /><style type="text/css">\np, li { white-space: pre-wrap; }\n</style></head><body style=" font-family:\'Lucida Grande\'; font-size:13pt; font-weight:400; font-style:normal;">\n<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;">properties</p></body></html>',
          'position': [-1022.0, -318.0],
          'rectP2': (394.625, 76.5),
          'text': u'properties'},
   '__in__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None},
   '__out__': {  'position': [0, 0], 'useUserColor': True, 'userColor': None}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




