# -*-python-*-

import os
from openalea.sconsx import config, environ


ALEASolution = config.ALEASolution

pj = os.path.join

name = 'starter'

SConsignFile()


options = Options(['../options.py', 'options.py'], ARGUMENTS)
tools = ['boost_python']

env = ALEASolution(options, tools)

# Set build directory
prefix = env['build_prefix']

# Build stage
SConscript(pj(prefix,"src/cpp/SConscript"), exports="env")
SConscript(pj(prefix,"src/wrapper/SConscript"), exports="env")

Default("build")
