# -*-python-*-
import os, re

Import("env")

# 1. Select and install the headers

includes = env.ALEAGlob('*.h', dir='../include')
env.ALEAIncludes("starter", includes)

# Build shared libraries

# 1. If you have only one shared library:
# sources = env.ALEAGlob('*.cpp')

# 2. Build first library
sources = "scene_object.cpp"
target = "sceneobject"

# Add defines to export symbols on Windows
DEFINES = list(env['CPPDEFINES'])
DEFINES.append('SCENEOBJ_DLL')

# Build the library
lib1 = env.ALEALibrary(target, sources, CPPDEFINES=DEFINES)

# 3. Build the second library
env2 = env.Clone()
env2.AppendUnique(LIBS= ["sceneobject"])

sources = ["scene_container.cpp"]
target = "scenecontainer"

DEFINES = list(env['CPPDEFINES'])
DEFINES.append('SCENECONT_DLL')

lib2 = env2.ALEALibrary(target, sources, CPPDEFINES=DEFINES)

