# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/mainwindow.ui'
#
# Created: Fri Aug  6 13:21:26 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from openalea.vpltk.qt import qt

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 593)
        icon = qt.QtGui.QIcon()
        icon.addPixmap(qt.QtGui.QPixmap(":/icons/openalea_icon.png"), qt.QtGui.QIcon.Normal, qt.QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = qt.QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = qt.QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.splitter_3 = qt.QtGui.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(qt.QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = qt.QtGui.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(qt.QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.tabPackager = qt.QtGui.QTabWidget(self.splitter_2)
        self.tabPackager.setObjectName("tabPackager")
        self.packageview = qt.QtGui.QWidget()
        self.packageview.setObjectName("packageview")
        self.vboxlayout1 = qt.QtGui.QVBoxLayout(self.packageview)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setContentsMargins(6, 6, 6, 6)
        self.vboxlayout1.setObjectName("vboxlayout1")
        icon1 = qt.QtGui.QIcon()
        icon1.addPixmap(qt.QtGui.QPixmap(":/icons/package.png"), qt.QtGui.QIcon.Normal, qt.QtGui.QIcon.Off)
        self.tabPackager.addTab(self.packageview, icon1, "")
        self.categoryview = qt.QtGui.QWidget()
        self.categoryview.setObjectName("categoryview")
        self.vboxlayout2 = qt.QtGui.QVBoxLayout(self.categoryview)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setContentsMargins(6, 6, 6, 6)
        self.vboxlayout2.setObjectName("vboxlayout2")
        icon2 = qt.QtGui.QIcon()
        icon2.addPixmap(qt.QtGui.QPixmap(":/icons/category.png"), qt.QtGui.QIcon.Normal, qt.QtGui.QIcon.Off)
        self.tabPackager.addTab(self.categoryview, icon2, "")
        self.searchview = qt.QtGui.QWidget()
        self.searchview.setObjectName("searchview")
        self.vboxlayout3 = qt.QtGui.QVBoxLayout(self.searchview)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setContentsMargins(6, 6, 6, 6)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.search_lineEdit = qt.QtGui.QLineEdit(self.searchview)
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.vboxlayout3.addWidget(self.search_lineEdit)
        icon3 = qt.QtGui.QIcon()
        icon3.addPixmap(qt.QtGui.QPixmap(":/icons/search.png"), qt.QtGui.QIcon.Normal, qt.QtGui.QIcon.Off)
        self.tabPackager.addTab(self.searchview, icon3, "")
        self.poolTabWidget = qt.QtGui.QTabWidget(self.splitter_2)
        self.poolTabWidget.setObjectName("poolTabWidget")
        self.pooltab = qt.QtGui.QWidget()
        self.pooltab.setObjectName("pooltab")
        self.vboxlayout4 = qt.QtGui.QVBoxLayout(self.pooltab)
        self.vboxlayout4.setSpacing(6)
        self.vboxlayout4.setContentsMargins(6, 6, 6, 6)
        self.vboxlayout4.setObjectName("vboxlayout4")
        icon4 = qt.QtGui.QIcon()
        icon4.addPixmap(qt.QtGui.QPixmap(":/icons/datapool.png"), qt.QtGui.QIcon.Normal, qt.QtGui.QIcon.Off)
        self.poolTabWidget.addTab(self.pooltab, icon4, "")
        self.splitter = qt.QtGui.QSplitter(self.splitter_3)
        sizePolicy = qt.QtGui.QSizePolicy(qt.QtGui.QSizePolicy.Expanding, qt.QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(qt.QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWorkspace = qt.QtGui.QTabWidget(self.splitter)
        sizePolicy = qt.QtGui.QSizePolicy(qt.QtGui.QSizePolicy.Expanding, qt.QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.tabWorkspace.sizePolicy().hasHeightForWidth())
        self.tabWorkspace.setSizePolicy(sizePolicy)
        self.tabWorkspace.setObjectName("tabWorkspace")
        self.usetab = qt.QtGui.QWidget()
        self.usetab.setObjectName("usetab")
        self.vboxlayout5 = qt.QtGui.QVBoxLayout(self.usetab)
        self.vboxlayout5.setSpacing(6)
        self.vboxlayout5.setContentsMargins(6, 6, 6, 6)
        self.vboxlayout5.setObjectName("vboxlayout5")
        self.tabWorkspace.addTab(self.usetab, "")
        self.vboxlayout.addWidget(self.splitter_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = qt.QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(qt.QtCore.QRect(0, 0, 852, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = qt.QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Export = qt.QtGui.QMenu(self.menu_File)
        self.menu_Export.setObjectName("menu_Export")
        self.menuApplication = qt.QtGui.QMenu(self.menu_Export)
        self.menuApplication.setObjectName("menuApplication")
        self.menuLast_open = qt.QtGui.QMenu(self.menu_File)
        self.menuLast_open.setObjectName("menuLast_open")
        self.menuDataPool = qt.QtGui.QMenu(self.menubar)
        self.menuDataPool.setObjectName("menuDataPool")
        self.menu_Help = qt.QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Python = qt.QtGui.QMenu(self.menubar)
        self.menu_Python.setObjectName("menu_Python")
        self.menu_Workspace = qt.QtGui.QMenu(self.menubar)
        icon5 = qt.QtGui.QIcon()
        icon5.addPixmap(qt.QtGui.QPixmap(), qt.QtGui.QIcon.Normal, qt.QtGui.QIcon.Off)
        self.menu_Workspace.setWindowIcon(icon5)
        self.menu_Workspace.setObjectName("menu_Workspace")
        self.menuAlign = qt.QtGui.QMenu(self.menu_Workspace)
        self.menuAlign.setObjectName("menuAlign")
        self.menuColour = qt.QtGui.QMenu(self.menu_Workspace)
        self.menuColour.setObjectName("menuColour")
        self.menu_Package = qt.QtGui.QMenu(self.menubar)
        self.menu_Package.setObjectName("menu_Package")
        self.menuCreate = qt.QtGui.QMenu(self.menu_Package)
        self.menuCreate.setObjectName("menuCreate")
        self.menu_Window = qt.QtGui.QMenu(self.menubar)
        self.menu_Window.setObjectName("menu_Window")
        MainWindow.setMenuBar(self.menubar)
        self.action_About = qt.QtGui.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Help = qt.QtGui.QAction(MainWindow)
        self.action_Help.setObjectName("action_Help")
        self.action_Quit = qt.QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")
        self.action_New_Package = qt.QtGui.QAction(MainWindow)
        self.action_New_Package.setObjectName("action_New_Package")
        self.actionSystem_Search = qt.QtGui.QAction(MainWindow)
        self.actionSystem_Search.setObjectName("actionSystem_Search")
        self.action_Add_File = qt.QtGui.QAction(MainWindow)
        self.action_Add_File.setObjectName("action_Add_File")
        self.action_Auto_Search = qt.QtGui.QAction(MainWindow)
        self.action_Auto_Search.setObjectName("action_Auto_Search")
        self.action_Close_current_workspace = qt.QtGui.QAction(MainWindow)
        self.action_Close_current_workspace.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.action_Close_current_workspace.setObjectName("action_Close_current_workspace")
        self.action_Run = qt.QtGui.QAction(MainWindow)
        self.action_Run.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.action_Run.setObjectName("action_Run")
        self.action_New_Network = qt.QtGui.QAction(MainWindow)
        self.action_New_Network.setObjectName("action_New_Network")
        self.actionOpenAlea_Web = qt.QtGui.QAction(MainWindow)
        self.actionOpenAlea_Web.setObjectName("actionOpenAlea_Web")
        self.action_Execute_script = qt.QtGui.QAction(MainWindow)
        self.action_Execute_script.setObjectName("action_Execute_script")
        self.action_New_Session = qt.QtGui.QAction(MainWindow)
        self.action_New_Session.setObjectName("action_New_Session")
        self.action_Open_Session = qt.QtGui.QAction(MainWindow)
        self.action_Open_Session.setObjectName("action_Open_Session")
        self.action_Save_Session = qt.QtGui.QAction(MainWindow)
        self.action_Save_Session.setObjectName("action_Save_Session")
        self.actionSave_as = qt.QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.action_Export_to_Factory = qt.QtGui.QAction(MainWindow)
        self.action_Export_to_Factory.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.action_Export_to_Factory.setObjectName("action_Export_to_Factory")
        self.actionExport_to_Application = qt.QtGui.QAction(MainWindow)
        self.actionExport_to_Application.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.actionExport_to_Application.setObjectName("actionExport_to_Application")
        self.actionClear_Data_Pool = qt.QtGui.QAction(MainWindow)
        self.actionClear_Data_Pool.setObjectName("actionClear_Data_Pool")
        self.actionFind_Node = qt.QtGui.QAction(MainWindow)
        self.actionFind_Node.setObjectName("actionFind_Node")
        self.actionNew_Python_Node = qt.QtGui.QAction(MainWindow)
        self.actionNew_Python_Node.setObjectName("actionNew_Python_Node")
        self.actionNew_Package = qt.QtGui.QAction(MainWindow)
        self.actionNew_Package.setObjectName("actionNew_Package")
        self.action_EditNode = qt.QtGui.QAction(MainWindow)
        self.action_EditNode.setObjectName("action_EditNode")
        self.actionShow_Pool = qt.QtGui.QAction(MainWindow)
        self.actionShow_Pool.setObjectName("actionShow_Pool")
        self.action_OpenNode = qt.QtGui.QAction(MainWindow)
        self.action_OpenNode.setObjectName("action_OpenNode")
        self.action_Delete_2 = qt.QtGui.QAction(MainWindow)
        self.action_Delete_2.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.action_Delete_2.setObjectName("action_Delete_2")
        self.action_New_Empty_Workspace = qt.QtGui.QAction(MainWindow)
        self.action_New_Empty_Workspace.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.action_New_Empty_Workspace.setObjectName("action_New_Empty_Workspace")
        self.actionReload_from_Model = qt.QtGui.QAction(MainWindow)
        self.actionReload_from_Model.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.actionReload_from_Model.setObjectName("actionReload_from_Model")
        self.actionPreferences = qt.QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionConfigure_I_O = qt.QtGui.QAction(MainWindow)
        self.actionConfigure_I_O.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.actionConfigure_I_O.setObjectName("actionConfigure_I_O")
        self.actionGroup_Selection = qt.QtGui.QAction(MainWindow)
        self.actionGroup_Selection.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.actionGroup_Selection.setObjectName("actionGroup_Selection")
        self.actionOpen_Console = qt.QtGui.QAction(MainWindow)
        self.actionOpen_Console.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.actionOpen_Console.setObjectName("actionOpen_Console")
        self.action_Copy = qt.QtGui.QAction(MainWindow)
        self.action_Copy.setShortcutContext(qt.QtCore.Qt.WidgetShortcut)
        self.action_Copy.setObjectName("action_Copy")
        self.action_Paste = qt.QtGui.QAction(MainWindow)
        self.action_Paste.setShortcutContext(qt.QtCore.Qt.WidgetShortcut)
        self.action_Paste.setObjectName("action_Paste")
        self.action_Cut = qt.QtGui.QAction(MainWindow)
        self.action_Cut.setShortcutContext(qt.QtCore.Qt.WidgetShortcut)
        self.action_Cut.setObjectName("action_Cut")
        self.actionReset = qt.QtGui.QAction(MainWindow)
        self.actionReset.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.actionReset.setObjectName("actionReset")
        self.actionPreview_Application = qt.QtGui.QAction(MainWindow)
        self.actionPreview_Application.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.actionPreview_Application.setObjectName("actionPreview_Application")
        self.actionLeft_Panel = qt.QtGui.QAction(MainWindow)
        self.actionLeft_Panel.setObjectName("actionLeft_Panel")
        self.actionWorkspaces = qt.QtGui.QAction(MainWindow)
        self.actionWorkspaces.setObjectName("actionWorkspaces")
        self.actionDisplay_Package_Manager = qt.QtGui.QAction(MainWindow)
        self.actionDisplay_Package_Manager.setCheckable(True)
        self.actionDisplay_Package_Manager.setChecked(True)
        self.actionDisplay_Package_Manager.setObjectName("actionDisplay_Package_Manager")
        self.actionDisplay_Workspaces = qt.QtGui.QAction(MainWindow)
        self.actionDisplay_Workspaces.setCheckable(True)
        self.actionDisplay_Workspaces.setChecked(True)
        self.actionDisplay_Workspaces.setObjectName("actionDisplay_Workspaces")
        self.actionInvalidate = qt.QtGui.QAction(MainWindow)
        self.actionInvalidate.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.actionInvalidate.setObjectName("actionInvalidate")
        self.actionClea_r_Console = qt.QtGui.QAction(MainWindow)
        self.actionClea_r_Console.setObjectName("actionClea_r_Console")
        self.action_Image = qt.QtGui.QAction(MainWindow)
        self.action_Image.setObjectName("action_Image")
        self.action_Svg = qt.QtGui.QAction(MainWindow)
        self.action_Svg.setObjectName("action_Svg")
        self.action_Application = qt.QtGui.QAction(MainWindow)
        self.action_Application.setObjectName("action_Application")
        self.action_Data_File = qt.QtGui.QAction(MainWindow)
        self.action_Data_File.setObjectName("action_Data_File")
        self.actionShow_log = qt.QtGui.QAction(MainWindow)
        self.actionShow_log.setObjectName("actionShow_log")
        self.actionAlignHorizontally = qt.QtGui.QAction(MainWindow)
        self.actionAlignHorizontally.setObjectName("actionAlignHorizontally")
        self.actionAlignLeft = qt.QtGui.QAction(MainWindow)
        self.actionAlignLeft.setObjectName("actionAlignLeft")
        self.actionAlignRight = qt.QtGui.QAction(MainWindow)
        self.actionAlignRight.setObjectName("actionAlignRight")
        self.actionAlignMean = qt.QtGui.QAction(MainWindow)
        self.actionAlignMean.setObjectName("actionAlignMean")
        self.actionSetCustomColor = qt.QtGui.QAction(MainWindow)
        self.actionSetCustomColor.setObjectName("actionSetCustomColor")
        self.actionUseCustomColor = qt.QtGui.QAction(MainWindow)
        self.actionUseCustomColor.setCheckable(True)
        self.actionUseCustomColor.setObjectName("actionUseCustomColor")
        self.actionDistributeHorizontally = qt.QtGui.QAction(MainWindow)
        self.actionDistributeHorizontally.setObjectName("actionDistributeHorizontally")
        self.actionDistributeVertically = qt.QtGui.QAction(MainWindow)
        self.actionDistributeVertically.setObjectName("actionDistributeVertically")
        self.actionTo_script = qt.QtGui.QAction(MainWindow)
        self.actionTo_script.setShortcutContext(qt.QtCore.Qt.ApplicationShortcut)
        self.actionTo_script.setObjectName("actionTo_script")
        self.actionGf = qt.QtGui.QAction(MainWindow)
        self.actionGf.setObjectName("actionGf")
        self.menuApplication.addAction(self.actionPreview_Application)
        self.menuApplication.addAction(self.actionExport_to_Application)
        self.menu_Export.addAction(self.menuApplication.menuAction())
        self.menu_Export.addAction(self.actionTo_script)
        self.menu_Export.addSeparator()
        self.menu_Export.addAction(self.action_Image)
        self.menu_Export.addAction(self.action_Svg)
        self.menu_File.addAction(self.action_New_Empty_Workspace)
        self.menu_File.addAction(self.menuLast_open.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Export_to_Factory)
        self.menu_File.addAction(self.action_Close_current_workspace)
        self.menu_File.addAction(self.actionReload_from_Model)
        self.menu_File.addAction(self.menu_Export.menuAction())
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)
        self.menuDataPool.addAction(self.actionClear_Data_Pool)
        self.menu_Help.addAction(self.action_Help)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addAction(self.actionOpenAlea_Web)
        self.menu_Python.addAction(self.action_Execute_script)
        self.menu_Python.addAction(self.actionOpen_Console)
        self.menu_Python.addAction(self.actionClea_r_Console)
        self.menuAlign.addAction(self.actionAlignHorizontally)
        self.menuAlign.addAction(self.actionAlignLeft)
        self.menuAlign.addAction(self.actionAlignRight)
        self.menuAlign.addAction(self.actionAlignMean)
        self.menuAlign.addAction(self.actionDistributeHorizontally)
        self.menuAlign.addAction(self.actionDistributeVertically)
        self.menuColour.addAction(self.actionSetCustomColor)
        self.menuColour.addAction(self.actionUseCustomColor)
        self.menu_Workspace.addAction(self.action_Run)
        self.menu_Workspace.addAction(self.actionInvalidate)
        self.menu_Workspace.addAction(self.actionReset)
        self.menu_Workspace.addAction(self.actionConfigure_I_O)
        self.menu_Workspace.addSeparator()
        self.menu_Workspace.addAction(self.actionGroup_Selection)
        self.menu_Workspace.addAction(self.action_Copy)
        self.menu_Workspace.addAction(self.action_Cut)
        self.menu_Workspace.addAction(self.action_Paste)
        self.menu_Workspace.addAction(self.action_Delete_2)
        self.menu_Workspace.addSeparator()
        self.menu_Workspace.addAction(self.menuAlign.menuAction())
        self.menu_Workspace.addAction(self.menuColour.menuAction())
        self.menuCreate.addAction(self.actionNew_Package)
        self.menuCreate.addAction(self.action_New_Network)
        self.menuCreate.addAction(self.actionNew_Python_Node)
        self.menuCreate.addAction(self.action_Data_File)
        self.menu_Package.addAction(self.action_Add_File)
        self.menu_Package.addAction(self.action_Auto_Search)
        self.menu_Package.addAction(self.actionFind_Node)
        self.menu_Package.addSeparator()
        self.menu_Package.addAction(self.menuCreate.menuAction())
        self.menu_Package.addSeparator()
        self.menu_Package.addAction(self.actionShow_log)
        self.menu_Window.addAction(self.actionDisplay_Package_Manager)
        self.menu_Window.addAction(self.actionDisplay_Workspaces)
        self.menu_Window.addSeparator()
        self.menu_Window.addAction(self.actionPreferences)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Package.menuAction())
        self.menubar.addAction(self.menuDataPool.menuAction())
        self.menubar.addAction(self.menu_Workspace.menuAction())
        self.menubar.addAction(self.menu_Python.menuAction())
        self.menubar.addAction(self.menu_Window.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabPackager.setCurrentIndex(0)
        self.poolTabWidget.setCurrentIndex(0)
        self.tabWorkspace.setCurrentIndex(0)
        qt.QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(qt.QtGui.QApplication.translate("MainWindow", "VisuAlea", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.tabPackager.setTabText(self.tabPackager.indexOf(self.packageview), qt.QtGui.QApplication.translate("MainWindow", "Package", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.tabPackager.setTabText(self.tabPackager.indexOf(self.categoryview), qt.QtGui.QApplication.translate("MainWindow", "Category", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.tabPackager.setTabText(self.tabPackager.indexOf(self.searchview), qt.QtGui.QApplication.translate("MainWindow", "Search", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.poolTabWidget.setTabText(self.poolTabWidget.indexOf(self.pooltab), qt.QtGui.QApplication.translate("MainWindow", "DataPool", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.tabWorkspace.setTabText(self.tabWorkspace.indexOf(self.usetab), qt.QtGui.QApplication.translate("MainWindow", "Root", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(qt.QtGui.QApplication.translate("MainWindow", "&File", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menu_Export.setTitle(qt.QtGui.QApplication.translate("MainWindow", "&Export", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menuApplication.setTitle(qt.QtGui.QApplication.translate("MainWindow", "Application", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menuLast_open.setTitle(qt.QtGui.QApplication.translate("MainWindow", "Open recent", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menuDataPool.setTitle(qt.QtGui.QApplication.translate("MainWindow", "&DataPool", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(qt.QtGui.QApplication.translate("MainWindow", "&Help", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menu_Python.setTitle(qt.QtGui.QApplication.translate("MainWindow", "P&ython", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menu_Workspace.setTitle(qt.QtGui.QApplication.translate("MainWindow", "&Workspace", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menuAlign.setTitle(qt.QtGui.QApplication.translate("MainWindow", "Align", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menuColour.setTitle(qt.QtGui.QApplication.translate("MainWindow", "Color", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menu_Package.setTitle(qt.QtGui.QApplication.translate("MainWindow", "&Package Manager", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menuCreate.setTitle(qt.QtGui.QApplication.translate("MainWindow", "&Add", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.menu_Window.setTitle(qt.QtGui.QApplication.translate("MainWindow", "&Window", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_About.setText(qt.QtGui.QApplication.translate("MainWindow", "&About", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Help.setText(qt.QtGui.QApplication.translate("MainWindow", "&Help", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Help.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "F1", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(qt.QtGui.QApplication.translate("MainWindow", "&Quit", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_New_Package.setText(qt.QtGui.QApplication.translate("MainWindow", "&Create Package", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_New_Package.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionSystem_Search.setText(qt.QtGui.QApplication.translate("MainWindow", "System &Search", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Add_File.setText(qt.QtGui.QApplication.translate("MainWindow", "&Load Package/Directory", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Auto_Search.setText(qt.QtGui.QApplication.translate("MainWindow", "&Reload All packages", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Close_current_workspace.setText(qt.QtGui.QApplication.translate("MainWindow", "Close Current Workspace", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Close_current_workspace.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Run.setText(qt.QtGui.QApplication.translate("MainWindow", "&Run ", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Run.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_New_Network.setText(qt.QtGui.QApplication.translate("MainWindow", "&Composite Node", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionOpenAlea_Web.setText(qt.QtGui.QApplication.translate("MainWindow", "OpenAlea Web", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Execute_script.setText(qt.QtGui.QApplication.translate("MainWindow", "&Execute script", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_New_Session.setText(qt.QtGui.QApplication.translate("MainWindow", "&New Session", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_New_Session.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Open_Session.setText(qt.QtGui.QApplication.translate("MainWindow", "&Open Session", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Open_Session.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Save_Session.setText(qt.QtGui.QApplication.translate("MainWindow", "&Save Session", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Save_Session.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(qt.QtGui.QApplication.translate("MainWindow", "Save &as", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Export_to_Factory.setText(qt.QtGui.QApplication.translate("MainWindow", "&Save as Composite Node", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Export_to_Factory.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionExport_to_Application.setText(qt.QtGui.QApplication.translate("MainWindow", "Export to Application", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Data_Pool.setText(qt.QtGui.QApplication.translate("MainWindow", "Clear Data Pool", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Node.setText(qt.QtGui.QApplication.translate("MainWindow", "&Find Node", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionFind_Node.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+F", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Python_Node.setText(qt.QtGui.QApplication.translate("MainWindow", "Python &Node", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Package.setText(qt.QtGui.QApplication.translate("MainWindow", "&Package", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_EditNode.setText(qt.QtGui.QApplication.translate("MainWindow", "&Edit", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Pool.setText(qt.QtGui.QApplication.translate("MainWindow", "Show Pool", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionShow_Pool.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+D", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_OpenNode.setText(qt.QtGui.QApplication.translate("MainWindow", "&Open", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Delete_2.setText(qt.QtGui.QApplication.translate("MainWindow", "&Delete", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_New_Empty_Workspace.setText(qt.QtGui.QApplication.translate("MainWindow", "&New Empty Workspace", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_New_Empty_Workspace.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+T", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionReload_from_Model.setText(qt.QtGui.QApplication.translate("MainWindow", "Reload", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionReload_from_Model.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(qt.QtGui.QApplication.translate("MainWindow", "Preferences", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure_I_O.setText(qt.QtGui.QApplication.translate("MainWindow", "Configure I/O", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionGroup_Selection.setText(qt.QtGui.QApplication.translate("MainWindow", "Group", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionGroup_Selection.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+G", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Console.setText(qt.QtGui.QApplication.translate("MainWindow", "Open &shell", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Console.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Copy.setText(qt.QtGui.QApplication.translate("MainWindow", "Copy", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Copy.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+C", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Paste.setText(qt.QtGui.QApplication.translate("MainWindow", "&Paste", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Paste.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Cut.setText(qt.QtGui.QApplication.translate("MainWindow", "Cut", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Cut.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+X", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setText(qt.QtGui.QApplication.translate("MainWindow", "Reset", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionReset.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+K", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionPreview_Application.setText(qt.QtGui.QApplication.translate("MainWindow", "Preview Application", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionLeft_Panel.setText(qt.QtGui.QApplication.translate("MainWindow", "Package Manager", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionWorkspaces.setText(qt.QtGui.QApplication.translate("MainWindow", "Workspaces", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionDisplay_Package_Manager.setText(qt.QtGui.QApplication.translate("MainWindow", "Display Package Manager", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionDisplay_Workspaces.setText(qt.QtGui.QApplication.translate("MainWindow", "Display Workspaces", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionInvalidate.setText(qt.QtGui.QApplication.translate("MainWindow", "Invalidate", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionInvalidate.setShortcut(qt.QtGui.QApplication.translate("MainWindow", "Ctrl+I", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionClea_r_Console.setText(qt.QtGui.QApplication.translate("MainWindow", "&Clear shell", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Image.setText(qt.QtGui.QApplication.translate("MainWindow", "&Image", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Svg.setText(qt.QtGui.QApplication.translate("MainWindow", "&Svg", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Application.setText(qt.QtGui.QApplication.translate("MainWindow", "&Application", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.action_Data_File.setText(qt.QtGui.QApplication.translate("MainWindow", "&Data File", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionShow_log.setText(qt.QtGui.QApplication.translate("MainWindow", "Show log", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionAlignHorizontally.setText(qt.QtGui.QApplication.translate("MainWindow", "Align Horizontally", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionAlignLeft.setText(qt.QtGui.QApplication.translate("MainWindow", "Align Left", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionAlignRight.setText(qt.QtGui.QApplication.translate("MainWindow", "Align Right", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionAlignMean.setText(qt.QtGui.QApplication.translate("MainWindow", "Align Mean", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionSetCustomColor.setText(qt.QtGui.QApplication.translate("MainWindow", "Set Custom Color...", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionSetCustomColor.setToolTip(qt.QtGui.QApplication.translate("MainWindow", "Set Custom Colour", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionUseCustomColor.setText(qt.QtGui.QApplication.translate("MainWindow", "Use Custom Color", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionUseCustomColor.setToolTip(qt.QtGui.QApplication.translate("MainWindow", "Use Custom Color", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionDistributeHorizontally.setText(qt.QtGui.QApplication.translate("MainWindow", "Distribute Horizontally", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionDistributeVertically.setText(qt.QtGui.QApplication.translate("MainWindow", "Distribute Vertically", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionDistributeVertically.setToolTip(qt.QtGui.QApplication.translate("MainWindow", "DistributeVertically", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionTo_script.setText(qt.QtGui.QApplication.translate("MainWindow", "Script", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.actionGf.setText(qt.QtGui.QApplication.translate("MainWindow", "gf", None, qt.QtGui.QApplication.UnicodeUTF8))

import images_rc
