# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newpackage.ui'
#
# Created: Wed Oct 22 16:38:33 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from openalea.vpltk.qt import qt

class Ui_NewPackageDialog(object):
    def setupUi(self, NewPackageDialog):
        NewPackageDialog.setObjectName("NewPackageDialog")
        NewPackageDialog.resize(479, 435)
        self.vboxlayout = qt.QtGui.QVBoxLayout(NewPackageDialog)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setObjectName("vboxlayout")
        self.gridlayout = qt.QtGui.QGridLayout()
        self.gridlayout.setContentsMargins(0, 0, 0, 0)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.authorsEdit = qt.QtGui.QLineEdit(NewPackageDialog)
        self.authorsEdit.setObjectName("authorsEdit")
        self.gridlayout.addWidget(self.authorsEdit, 4, 1, 1, 1)
        self.label_2 = qt.QtGui.QLabel(NewPackageDialog)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pathButton = qt.QtGui.QPushButton(NewPackageDialog)
        self.pathButton.setObjectName("pathButton")
        self.gridlayout.addWidget(self.pathButton, 7, 2, 1, 1)
        self.label = qt.QtGui.QLabel(NewPackageDialog)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.versionEdit = qt.QtGui.QLineEdit(NewPackageDialog)
        self.versionEdit.setObjectName("versionEdit")
        self.gridlayout.addWidget(self.versionEdit, 2, 1, 1, 1)
        self.label_7 = qt.QtGui.QLabel(NewPackageDialog)
        self.label_7.setObjectName("label_7")
        self.gridlayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_8 = qt.QtGui.QLabel(NewPackageDialog)
        self.label_8.setObjectName("label_8")
        self.gridlayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.pathEdit = qt.QtGui.QLineEdit(NewPackageDialog)
        self.pathEdit.setObjectName("pathEdit")
        self.gridlayout.addWidget(self.pathEdit, 7, 1, 1, 1)
        self.label_6 = qt.QtGui.QLabel(NewPackageDialog)
        self.label_6.setObjectName("label_6")
        self.gridlayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.descriptionEdit = qt.QtGui.QLineEdit(NewPackageDialog)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridlayout.addWidget(self.descriptionEdit, 1, 1, 1, 1)
        self.label_3 = qt.QtGui.QLabel(NewPackageDialog)
        self.label_3.setObjectName("label_3")
        self.gridlayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.institutesEdit = qt.QtGui.QLineEdit(NewPackageDialog)
        self.institutesEdit.setObjectName("institutesEdit")
        self.gridlayout.addWidget(self.institutesEdit, 5, 1, 1, 1)
        self.urlEdit = qt.QtGui.QLineEdit(NewPackageDialog)
        self.urlEdit.setObjectName("urlEdit")
        self.gridlayout.addWidget(self.urlEdit, 6, 1, 1, 1)
        self.label_4 = qt.QtGui.QLabel(NewPackageDialog)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.nameEdit = qt.QtGui.QLineEdit(NewPackageDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.gridlayout.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.label_5 = qt.QtGui.QLabel(NewPackageDialog)
        self.label_5.setObjectName("label_5")
        self.gridlayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.licenseEdit = qt.QtGui.QLineEdit(NewPackageDialog)
        self.licenseEdit.setObjectName("licenseEdit")
        self.gridlayout.addWidget(self.licenseEdit, 3, 1, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.buttonBox = qt.QtGui.QDialogButtonBox(NewPackageDialog)
        self.buttonBox.setOrientation(qt.QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(qt.QtGui.QDialogButtonBox.Cancel|qt.QtGui.QDialogButtonBox.NoButton|qt.QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(NewPackageDialog)
        qt.QtCore.QObject.connect(self.buttonBox, qt.QtCore.SIGNAL("accepted()"), NewPackageDialog.accept)
        qt.QtCore.QObject.connect(self.buttonBox, qt.QtCore.SIGNAL("rejected()"), NewPackageDialog.reject)
        qt.QtCore.QMetaObject.connectSlotsByName(NewPackageDialog)
        NewPackageDialog.setTabOrder(self.nameEdit, self.descriptionEdit)
        NewPackageDialog.setTabOrder(self.descriptionEdit, self.versionEdit)
        NewPackageDialog.setTabOrder(self.versionEdit, self.licenseEdit)
        NewPackageDialog.setTabOrder(self.licenseEdit, self.authorsEdit)
        NewPackageDialog.setTabOrder(self.authorsEdit, self.institutesEdit)
        NewPackageDialog.setTabOrder(self.institutesEdit, self.urlEdit)
        NewPackageDialog.setTabOrder(self.urlEdit, self.pathEdit)
        NewPackageDialog.setTabOrder(self.pathEdit, self.pathButton)
        NewPackageDialog.setTabOrder(self.pathButton, self.buttonBox)

    def retranslateUi(self, NewPackageDialog):
        NewPackageDialog.setWindowTitle(qt.QtGui.QApplication.translate("NewPackageDialog", "Package", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(qt.QtGui.QApplication.translate("NewPackageDialog", "Description", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.pathButton.setText(qt.QtGui.QApplication.translate("NewPackageDialog", "...", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.label.setText(qt.QtGui.QApplication.translate("NewPackageDialog", "Name", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(qt.QtGui.QApplication.translate("NewPackageDialog", "URL", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(qt.QtGui.QApplication.translate("NewPackageDialog", "Path", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(qt.QtGui.QApplication.translate("NewPackageDialog", "Institutes", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(qt.QtGui.QApplication.translate("NewPackageDialog", "Version", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(qt.QtGui.QApplication.translate("NewPackageDialog", "License", None, qt.QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(qt.QtGui.QApplication.translate("NewPackageDialog", "Authors", None, qt.QtGui.QApplication.UnicodeUTF8))

