
# This file has been generated at $TIME

from openalea.core import *

def register_packages(pkgmanager):
    
    metainfo = {'description': '', 'license': '', 'url': '', 'version': '', 'authors': '', 'institutes': ''} 
    pkg = UserPackage("Demo.Caribu", metainfo)

    

    nf = CompositeNodeFactory(name='demo', 
                              description='', 
                              category='Stat',
                              doc='',
                              inputs=[],
                              outputs=[],
                              elt_factory=\
{2: ('Caribu.Aggregate', 'can scene'),
 3: ('Catalog.Python', 'len'),
 4: ('Caribu.Aggregate', 'aggregate'),
 5: ('Catalog.Data', 'int'),
 6: ('Catalog.Python', 'len'),
 7: ('Catalog.Functional', 'function'),
 8: ('Catalog.Data', 'int'),
 9: ('Catalog.Data', 'int')},
                              elt_connections=\
{9723736: (8, 0, 4, 2),
 9723748: (9, 0, 4, 1),
 9723760: (8, 0, 4, 1),
 9723772: (6, 0, 5, 0),
 9723784: (2, 0, 6, 0),
 9723796: (7, 0, 4, 3),
 9723808: (2, 0, 4, 0),
 9723820: (2, 1, 3, 0)},
                              elt_data=\
{2: {'caption': 'can scene',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 127.5,
     'posy': 48.75,
     'priority': 0},
 3: {'caption': 'len',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 278.75,
     'posy': 83.75,
     'priority': 0},
 4: {'caption': 'aggregate',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 207.5,
     'posy': 275.0,
     'priority': 0},
 5: {'caption': '6',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 70.0,
     'posy': 217.5,
     'priority': 0},
 6: {'caption': 'len',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 63.75,
     'posy': 146.25,
     'priority': 0},
 7: {'caption': 'function',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 537.5,
     'posy': 186.25,
     'priority': 0},
 8: {'caption': '4',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 270.0,
     'posy': 167.5,
     'priority': 0},
 9: {'caption': '3',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 230.0,
     'posy': 171.25,
     'priority': 0},
 '__in__': {'caption': 'In',
            'hide': True,
            'lazy': True,
            'minimal': False,
            'port_hide_changed': set([]),
            'posx': 20.0,
            'posy': 5.0,
            'priority': 0},
 '__out__': {'caption': 'Out',
             'hide': True,
             'lazy': True,
             'minimal': False,
             'port_hide_changed': set([]),
             'posx': 20.0,
             'posy': 250.0,
             'priority': 0}},
                              elt_value=\
{2: [(0, "'D:/pradal/devlp/alea/openalea/trunk/demo/caribu/scene.can'")],
 3: [],
 4: [],
 5: [],
 6: [],
 7: [(0, "'def f(organ_id, opt_id, inds):\\n   return len(inds)'")],
 8: [(0, '4')],
 9: [(0, '3')],
 '__in__': [],
 '__out__': []},
                              lazy=True,
                              )

    pkg.add_factory(nf)


    nf = CompositeNodeFactory(name='ViewMapOnCan', 
                              description='', 
                              category='Visualisation.Color',
                              doc='',
                              inputs=\
[{'interface': IFileStr, 'name': 'CanFile', 'value': None},
 {'interface': IFileStr, 'name': 'VecFile', 'value': None}],
                              outputs=[{'interface': IFileStr, 'name': 'CanFile'}],
                              elt_factory=\
{2: ('Catalog.Math', 'min'),
 3: ('Caribu.Visualisation', 'Read Vec File'),
 4: ('Catalog.Math', 'max'),
 5: ('Catalog.Color', 'ColorMap'),
 6: ('Catalog.Functional', 'map'),
 7: ('Caribu.Visualisation', 'Plot Can File')},
                              elt_connections=\
{9723712: (7, 0, '__out__', 0),
 9723724: (3, 0, 6, 1),
 9723736: (5, 0, 6, 0),
 9723748: (3, 0, 2, 0),
 9723760: (4, 0, 5, 2),
 9723772: ('__in__', 0, 7, 0),
 9723784: (6, 0, 7, 1),
 9723796: (3, 0, 4, 0),
 9723808: ('__in__', 1, 3, 0),
 9723820: (2, 0, 5, 1)},
                              elt_data=\
{2: {'caption': 'min',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 347.5,
     'posy': 128.75,
     'priority': 0},
 3: {'caption': 'Read Vec File',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 351.25,
     'posy': 31.25,
     'priority': 0},
 4: {'caption': 'max',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 435.0,
     'posy': 128.75,
     'priority': 0},
 5: {'caption': 'ColorMap',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 360.0,
     'posy': 225.0,
     'priority': 0},
 6: {'caption': 'map',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 501.25,
     'posy': 272.5,
     'priority': 0},
 7: {'caption': 'Plot Can File',
     'hide': True,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 318.75,
     'posy': 321.25,
     'priority': 0},
 '__in__': {'caption': 'In',
            'hide': True,
            'lazy': True,
            'minimal': False,
            'port_hide_changed': set([]),
            'posx': 205.0,
            'posy': 27.5,
            'priority': 0},
 '__out__': {'caption': 'Out',
             'hide': True,
             'lazy': True,
             'minimal': False,
             'port_hide_changed': set([]),
             'posx': 346.25,
             'posy': 378.75,
             'priority': 0}},
                              elt_value=\
{2: [],
 3: [],
 4: [],
 5: [(0, 'None'), (3, '250.0'), (4, '20.0')],
 6: [],
 7: [],
 '__in__': [],
 '__out__': []},
                              lazy=True,
                              )

    pkg.add_factory(nf)


    nf = CompositeNodeFactory(name='CaribuFiles', 
                              description='', 
                              category='Unclassified',
                              doc='',
                              inputs=\
[{'interface': IFileStr, 'name': 'FileStr', 'value': ''},
 {'hide': True, 'interface': IDirStr, 'name': 'cwd', 'value': ''},
 {'interface': IFileStr, 'name': 'FileStr', 'value': ''},
 {'hide': True, 'interface': IDirStr, 'name': 'cwd', 'value': ''},
 {'interface': IFileStr, 'name': 'FileStr', 'value': ''},
 {'hide': True, 'interface': IDirStr, 'name': 'cwd', 'value': ''}],
                              outputs=\
[{'interface': IFileStr, 'name': 'FileStr'},
 {'interface': IFileStr, 'name': 'FileStr'},
 {'interface': IFileStr, 'name': 'FileStr'}],
                              elt_factory=\
{7: ('Catalog.Data', 'filename'),
 8: ('Catalog.Data', 'filename'),
 9: ('Catalog.Data', 'filename')},
                              elt_connections=\
{20843616: ('__in__', 1, 7, 1),
 53472640: ('__in__', 2, 8, 0),
 53472880: ('__in__', 3, 8, 1),
 53473216: ('__in__', 4, 9, 0),
 54076736: ('__in__', 5, 9, 1),
 54076784: (7, 0, '__out__', 0),
 54076832: (8, 0, '__out__', 1),
 54076880: (9, 0, '__out__', 2),
 54078080: ('__in__', 0, 7, 0)},
                              elt_data=\
{7: {'caption': 'CanFile',
     'hide': False,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 26.25,
     'posy': 36.25,
     'priority': 0},
 8: {'caption': 'LightFile',
     'hide': False,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 290.0,
     'posy': 38.75,
     'priority': 0},
 9: {'caption': 'OpticalFile',
     'hide': False,
     'lazy': True,
     'minimal': False,
     'port_hide_changed': set([]),
     'posx': 163.75,
     'posy': 36.25,
     'priority': 0}},
                              elt_value=\
{7: [(0, "'D:/Christian/Softs/WinCaribu_4.4/Tout.can'"), (1, "''")],
 8: [(0,
      "'D:/Christian/Softs/2006_pycaribu/trunk/test/par_Plop_sources.light'"),
     (1, "''")],
 9: [(0, "'D:/Christian/Softs/WinCaribu_4.4/par.opt'"), (1, "''")]},
                              lazy=True,
                              )

    pkg.add_factory(nf)


    pkgmanager.add_package(pkg)


