"""Some parameters"""


scale = {'linear':'linear',
    'log':'log',
    'symlog':'symlog'}










"""from matplotlib.pyplot import rcParams:
{'agg.path.chunksize': 0,
 'axes.axisbelow': False,
 'axes.color_cycle': ['b', 'g', 'r', 'c', 'm', 'y', 'k'],
 'axes.edgecolor': 'k',
 'axes.facecolor': 'w',
 'axes.formatter.limits': [-7, 7],
 'axes.grid': False,
 'axes.hold': True,
 'axes.labelcolor': 'k',
 'axes.labelsize': 'medium',
 'axes.linewidth': 1.0,
 'axes.titlesize': 'large',
 'axes.unicode_minus': True,
 'axes3d.grid': True,
 'backend': 'Qt4Agg',
 'backend_fallback': True,
 'cairo.format': 'png',
 'contour.negative_linestyle': 'dashed',
 'datapath': '/home/cokelaer/Work/virtualplants/trunk/lib/python2.6/site-packages/matplotlib-1.0.0-py2.6-linux-i686.egg/matplotlib/mpl-data',
 'docstring.hardcopy': False,
 'figure.autolayout': False,
 'figure.dpi': 80,
 'figure.edgecolor': 'w',
 'figure.facecolor': '0.75',
 'figure.figsize': [8.0, 6.0],
 'figure.subplot.bottom': 0.10000000000000001,
 'figure.subplot.hspace': 0.20000000000000001,
 'figure.subplot.left': 0.125,
 'figure.subplot.right': 0.90000000000000002,
 'figure.subplot.top': 0.90000000000000002,
 'figure.subplot.wspace': 0.20000000000000001,
 'font.cursive': ['Apple Chancery',
                  'Textile',
                  'Zapf Chancery',
                  'Sand',
                  'cursive'],
 'font.family': 'sans-serif',
 'font.fantasy': ['Comic Sans MS',
                  'Chicago',
                  'Charcoal',
                  'ImpactWestern',
                  'fantasy'],
 'font.monospace': ['Bitstream Vera Sans Mono',
                    'DejaVu Sans Mono',
                    'Andale Mono',
                    'Nimbus Mono L',
                    'Courier New',
                    'Courier',
                    'Fixed',
                    'Terminal',
                    'monospace'],
 'font.sans-serif': ['Bitstream Vera Sans',
                     'DejaVu Sans',
                     'Lucida Grande',
                     'Verdana',
                     'Geneva',
                     'Lucid',
                     'Arial',
                     'Helvetica',
                     'Avant Garde',
                     'sans-serif'],
 'font.serif': ['Bitstream Vera Serif',
                'DejaVu Serif',
                'New Century Schoolbook',
                'Century Schoolbook L',
                'Utopia',
                'ITC Bookman',
                'Bookman',
                'Nimbus Roman No9 L',
                'Times New Roman',
                'Times',
                'Palatino',
                'Charter',
                'serif'],
 'font.size': 12.0,
 'font.stretch': 'normal',
 'font.style': 'normal',
 'font.variant': 'normal',
 'font.weight': 'normal',
 'grid.color': 'k',
 'grid.linestyle': ':',
 'grid.linewidth': 0.5,
 'image.aspect': 'equal',
 'image.cmap': 'jet',
 'image.interpolation': 'bilinear',
 'image.lut': 256,
 'image.origin': 'upper',
 'image.resample': False,
 'interactive': True,
 'keymap.all_axes': 'a',
 'keymap.back': ['left', 'c', 'backspace'],
 'keymap.forward': ['right', 'v'],
 'keymap.fullscreen': 'f',
 'keymap.grid': 'g',
 'keymap.home': ['h', 'r', 'home'],
 'keymap.pan': 'p',
 'keymap.save': 's',
 'keymap.xscale': ['k', 'L'],
 'keymap.yscale': 'l',
 'keymap.zoom': 'o',
 'legend.borderaxespad': 0.5,
 'legend.borderpad': 0.40000000000000002,
 'legend.columnspacing': 2.0,
 'legend.fancybox': False,
 'legend.fontsize': 'large',
 'legend.handlelength': 2.0,
 'legend.handletextpad': 0.80000000000000004,
 'legend.isaxes': True,
 'legend.labelspacing': 0.5,
 'legend.loc': 'upper right',
 'legend.markerscale': 1.0,
 'legend.numpoints': 2,
 'legend.shadow': False,
 'lines.antialiased': True,
 'lines.color': 'b',
 'lines.dash_capstyle': 'butt',
 'lines.dash_joinstyle': 'round',
 'lines.linestyle': '-',
 'lines.linewidth': 1.0,
 'lines.marker': 'None',
 'lines.markeredgewidth': 0.5,
 'lines.markersize': 6,
 'lines.solid_capstyle': 'projecting',
 'lines.solid_joinstyle': 'round',
 'maskedarray': 'obsolete',
 'mathtext.bf': 'serif:bold',
 'mathtext.cal': 'cursive',
 'mathtext.default': 'it',
 'mathtext.fallback_to_cm': True,
 'mathtext.fontset': 'cm',
 'mathtext.it': 'serif:italic',
 'mathtext.rm': 'serif',
 'mathtext.sf': 'sans\\-serif',
 'mathtext.tt': 'monospace',
 'numerix': 'obsolete',
 'patch.antialiased': True,
 'patch.edgecolor': 'k',
 'patch.facecolor': 'b',
 'patch.linewidth': 1.0,
 'path.simplify': True,
 'path.simplify_threshold': 0.1111111111111111,
 'path.snap': True,
 'pdf.compression': 6,
 'pdf.fonttype': 3,
 'pdf.inheritcolor': False,
 'pdf.use14corefonts': False,
 'plugins.directory': '.matplotlib_plugins',
 'polaraxes.grid': True,
 'ps.distiller.res': 6000,
 'ps.fonttype': 3,
 'ps.papersize': 'letter',
 'ps.useafm': False,
 'ps.usedistiller': False,
 'savefig.dpi': 100,
 'savefig.edgecolor': 'w',
 'savefig.extension': 'auto',
 'savefig.facecolor': 'w',
 'savefig.orientation': 'portrait',
 'svg.embed_char_paths': True,
 'svg.image_inline': True,
 'svg.image_noscale': False,
 'text.color': 'k',
 'text.dvipnghack': None,
 'text.fontangle': 'normal',
 'text.fontsize': 'medium',
 'text.fontstyle': 'normal',
 'text.fontvariant': 'normal',
 'text.fontweight': 'normal',
 'text.hinting': True,
 'text.latex.preamble': [''],
 'text.latex.preview': False,
 'text.latex.unicode': False,
 'text.usetex': False,
 'timezone': 'UTC',
 'tk.pythoninspect': False,
 'tk.window_focus': False,
 'toolbar': 'toolbar2',
 'units': False,
 'verbose.fileo': 'sys.stdout',
 'verbose.level': 'silent',
 'xtick.color': 'k',
 'xtick.direction': 'in',
 'xtick.labelsize': 'medium',
 'xtick.major.pad': 4,
 'xtick.major.size': 4,
 'xtick.minor.pad': 4,
 'xtick.minor.size': 2,
 'ytick.color': 'k',
 'ytick.direction': 'in',
 'ytick.labelsize': 'medium',
 'ytick.major.pad': 4,
 'ytick.major.size': 4,
 'ytick.minor.pad': 4,
 'ytick.minor.size': 2}
"""